/**
 * Stripe webhook — signature verification + idempotent status sync (FASE 4e).
 *
 * Signature verification is tested against the REAL Stripe SDK (faithful
 * boundary, lesson TER-369): a header generated by Stripe.webhooks
 * .generateTestHeaderString must verify, and a tampered one must throw. The
 * status-sync logic (applyStripeWebhookEvent) is tested directly with seeded
 * invoices.
 *
 * MUST BITE:
 *   - drop the dedup insert → the "redelivery is a no-op" test goes red
 *     (a second invoice.paid would re-touch state).
 *   - let invoice.payment_failed overwrite a 'paid' invoice → the guard test red.
 *   - skip persisting invoiceNumber on paid → that assertion red.
 */

import { describe, expect, it } from 'bun:test'
import { createHmac } from 'crypto'
import type { Db } from 'mongodb'
import { createStripeClient } from '../../src/services/stripe-client'
import { applyStripeWebhookEvent } from '../../src/handlers/stripe-webhook-handler'
import type { StripeEventRef } from '../../src/services/stripe-api'
import { InMemoryDb } from './_stripe-test-helpers'

const WEBHOOK_SECRET = 'whsec_test_secret'

/** Build a genuine Stripe-Signature header (scheme: t=<ts>,v1=<hmac>). */
function signPayload(payload: string, secret: string): string {
  // Current timestamp so it falls within constructEvent's default 300s tolerance.
  const timestamp = Math.floor(Date.now() / 1000)
  const sig = createHmac('sha256', secret).update(`${timestamp}.${payload}`).digest('hex')
  return `t=${timestamp},v1=${sig}`
}

function event(type: string, object: Record<string, unknown>, id = 'evt_1'): StripeEventRef {
  return { id, type, data: { object } }
}

function invoiceDoc(over: Record<string, any> = {}) {
  const now = new Date('2026-06-10T00:00:00Z')
  return {
    _id: 'inv_1',
    subscriptionId: 'sub_1',
    userId: 'user_1',
    periodStart: new Date('2026-05-10T00:00:00Z'),
    periodEnd: new Date('2026-06-10T00:00:00Z'),
    amount: 89,
    currency: 'EUR',
    status: 'overdue',
    paymentMethod: 'stripe',
    invoiceNumber: null,
    externalReference: 'in_stripe_1',
    notes: '',
    createdAt: now,
    updatedAt: now,
    ...over,
  }
}

describe('Stripe webhook signature verification (real SDK boundary)', () => {
  it('verifies a genuine signature and rejects a tampered one', async () => {
    const adapter = createStripeClient({ secretKey: 'sk_test_dummy', webhookSecret: WEBHOOK_SECRET })!
    const payload = JSON.stringify({ id: 'evt_x', type: 'invoice.paid', data: { object: { id: 'in_1' } } })
    const header = signPayload(payload, WEBHOOK_SECRET)

    const parsed = await adapter.constructWebhookEvent(payload, header)
    expect(parsed.id).toBe('evt_x')
    expect(parsed.type).toBe('invoice.paid')

    // Wrong secret → signature mismatch → rejected.
    const forged = signPayload(payload, 'whsec_wrong_secret')
    await expect(adapter.constructWebhookEvent(payload, forged)).rejects.toThrow()
    // Tampered payload with a valid-for-the-original signature → rejected.
    await expect(adapter.constructWebhookEvent(payload + ' ', header)).rejects.toThrow()
  })
})

describe('applyStripeWebhookEvent', () => {
  const now = new Date('2026-06-15T00:00:00Z')

  it('marks the invoice paid and records the Stripe legal fields', async () => {
    const db = new InMemoryDb()
    db.seed('billing_invoices', [invoiceDoc()])

    const res = await applyStripeWebhookEvent(
      db as unknown as Db,
      event('invoice.paid', {
        id: 'in_stripe_1',
        number: 'TEROS-0007',
        hosted_invoice_url: 'https://pay/x',
        invoice_pdf: 'https://pay/x.pdf',
        metadata: { terosInvoiceId: 'inv_1' },
      }),
      now,
    )

    expect(res).toEqual({ handled: true, status: 'paid' })
    const stored = await db.collection('billing_invoices').findOne({ _id: 'inv_1' })
    expect(stored?.status).toBe('paid')
    expect(stored?.invoiceNumber).toBe('TEROS-0007')
    expect(stored?.hostedInvoiceUrl).toBe('https://pay/x')
    expect(stored?.lastChargeError).toBeNull()
  })

  it('is idempotent: a redelivered event is a no-op', async () => {
    const db = new InMemoryDb()
    db.seed('billing_invoices', [invoiceDoc()])
    const evt = event('invoice.paid', { id: 'in_stripe_1', metadata: { terosInvoiceId: 'inv_1' } })

    const first = await applyStripeWebhookEvent(db as unknown as Db, evt, now)
    const second = await applyStripeWebhookEvent(db as unknown as Db, evt, now)

    expect(first).toEqual({ handled: true, status: 'paid' })
    expect(second).toEqual({ deduped: true, handled: false })
  })

  it('rolls back the dedup claim when the apply throws, so a redelivery re-applies (TER-623)', async () => {
    const db = new InMemoryDb()
    db.seed('billing_invoices', [invoiceDoc()])
    const evt = event('invoice.paid', { id: 'in_stripe_1', metadata: { terosInvoiceId: 'inv_1' } })

    // First delivery: the invoice update throws (a transient Mongo blip) AFTER the
    // dedup slot was claimed.
    const invoicesCol = db.collection('billing_invoices')
    const realUpdate = invoicesCol.updateOne.bind(invoicesCol)
    let boom = true
    ;(invoicesCol as any).updateOne = async (...args: any[]) => {
      if (boom) {
        boom = false
        throw new Error('transient mongo blip')
      }
      return realUpdate(...args)
    }

    await expect(applyStripeWebhookEvent(db as unknown as Db, evt, now)).rejects.toThrow(/transient/)
    // The invoice is still unpaid (the apply failed)…
    expect((await db.collection('billing_invoices').findOne({ _id: 'inv_1' }))?.status).toBe('overdue')
    // …and the dedup slot was rolled back — the event is NOT recorded as processed.
    expect(await db.collection('billing_webhook_events').countDocuments({ _id: 'evt_1' })).toBe(0)

    // Redelivery now RE-APPLIES instead of being swallowed as a duplicate.
    const retry = await applyStripeWebhookEvent(db as unknown as Db, evt, now)
    expect(retry).toEqual({ handled: true, status: 'paid' })
    expect((await db.collection('billing_invoices').findOne({ _id: 'inv_1' }))?.status).toBe('paid')
    // MUST BITE: keep the old order (mark dedup, then apply, no rollback) → the
    // slot persists → the redelivery returns { deduped: true } and the invoice
    // stays overdue → "paid but blocked" forever.
  })

  it('marks a collectible invoice overdue on payment_failed', async () => {
    const db = new InMemoryDb()
    db.seed('billing_invoices', [invoiceDoc({ status: 'pending' })])

    const res = await applyStripeWebhookEvent(
      db as unknown as Db,
      event('invoice.payment_failed', { id: 'in_stripe_1', metadata: { terosInvoiceId: 'inv_1' } }),
      now,
    )

    expect(res).toEqual({ handled: true, status: 'overdue' })
    expect((await db.collection('billing_invoices').findOne({ _id: 'inv_1' }))?.status).toBe('overdue')
  })

  it('never overwrites a paid invoice on a late payment_failed', async () => {
    const db = new InMemoryDb()
    db.seed('billing_invoices', [invoiceDoc({ status: 'paid' })])

    const res = await applyStripeWebhookEvent(
      db as unknown as Db,
      event('invoice.payment_failed', { id: 'in_stripe_1', metadata: { terosInvoiceId: 'inv_1' } }),
      now,
    )

    expect(res).toEqual({ handled: true, status: 'paid' })
    expect((await db.collection('billing_invoices').findOne({ _id: 'inv_1' }))?.status).toBe('paid')
  })

  it('resolves the invoice by Stripe id when metadata is absent', async () => {
    const db = new InMemoryDb()
    db.seed('billing_invoices', [invoiceDoc({ status: 'pending' })])

    const res = await applyStripeWebhookEvent(
      db as unknown as Db,
      event('invoice.paid', { id: 'in_stripe_1' }), // no metadata
      now,
    )

    expect(res.status).toBe('paid')
  })

  it('ignores unhandled event types', async () => {
    const db = new InMemoryDb()
    const res = await applyStripeWebhookEvent(
      db as unknown as Db,
      event('customer.created', { id: 'cus_1' }),
      now,
    )
    expect(res.handled).toBe(false)
  })
})
