/**
 * Sync MCAs Script
 *
 * Reads manifest.json files from the mcas/ directory and syncs them
 * with the mca_catalog collection in MongoDB.
 *
 * Usage:
 *   npx tsx src/scripts/sync-mcas.ts [--dry-run]
 *
 * Options:
 *   --dry-run    Show what would be synced without making changes
 */

import { formatValidationResult, type MCAManifest, validateMCAManifest } from "@teros/shared"
import { readdir, readFile } from "fs/promises"
import { MongoClient } from "mongodb"
import { dirname, join } from "path"
import { fileURLToPath } from "url"
import { config } from "../config"
import { secrets } from "../secrets/secrets-manager"
import { McaService } from "../services/mca-service"
import type { McpCatalogEntry } from "../types/database"
import { getMcaStaticUrl } from "../utils/static-url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

// Path to MCAs directory (relative to teros-v2 root)
const MCAS_DIR = join(__dirname, "../../../../mcas")

/**
 * Tools.json schema (auto-generated by generate-mca-tools.ts)
 */
interface ToolsJson {
  $schema?: string
  mcaId: string
  tools: Array<{
    name: string
    description: string
    inputSchema: any
  }>
}

/**
 * Build the full icon URL from manifest icon field
 *
 * If icon is a relative path (e.g., 'icon.svg'), it's treated as an MCA static asset
 * If icon is already a full URL (starts with http), it's used as-is
 */
function buildIconUrl(mcaId: string, icon?: string): string | undefined {
  if (!icon) return undefined

  // If already a full URL, use as-is
  if (icon.startsWith("http://") || icon.startsWith("https://")) {
    return icon
  }

  // Otherwise, treat as relative path within MCA's static folder
  return getMcaStaticUrl(mcaId, icon)
}

/**
 * Extract auth configuration from layers for database storage
 */
function extractAuthConfig(manifest: MCAManifest): McpCatalogEntry["auth"] {
  const auth = manifest.layers.auth
  if (auth === false) return undefined

  if (auth.type === "oauth2") {
    return {
      type: "oauth2",
      provider: auth.provider,
      authorizeUrl: auth.authorizeUrl,
      tokenUrl: auth.tokenUrl,
      scopes: auth.scopes,
      pkce: auth.pkce,
    }
  }

  if (auth.type === "api-key") {
    return { type: "apikey" }
  }

  return undefined
}

/**
 * Extract secrets from layers for database storage
 */
function extractSecrets(manifest: MCAManifest): { systemSecrets: string[]; userSecrets: string[] } {
  const auth = manifest.layers.auth
  if (auth === false) {
    return { systemSecrets: [], userSecrets: [] }
  }
  return {
    systemSecrets: auth.systemSecrets || [],
    userSecrets: auth.userSecrets || [],
  }
}

/**
 * Convert manifest to catalog entry
 */
function manifestToCatalogEntry(
  manifest: MCAManifest,
  mcaDir: string,
  tools: string[],
): McpCatalogEntry {
  const now = new Date().toISOString()

  // Determine command based on entrypoint
  const entrypoint = manifest.entrypoint
  let command = "tsx"
  let args = [entrypoint]

  // If entrypoint is a .js file, use node directly
  if (entrypoint.endsWith(".js")) {
    command = "node"
    args = [entrypoint]
  }

  // Availability from manifest (now required)
  const availability = {
    enabled: manifest.availability.enabled,
    multi: manifest.availability.multi,
    system: manifest.availability.system,
    hidden: manifest.availability.hidden ?? false,
    role: manifest.availability.role,
  }

  // Extract auth and secrets from layers
  const { systemSecrets, userSecrets } = extractSecrets(manifest)
  const auth = extractAuthConfig(manifest)

  return {
    mcaId: manifest.id,
    name: manifest.name,
    description: manifest.description,
    execution: {
      command,
      args,
      cwd: mcaDir, // Directory name (e.g., 'mca.teros.bash')
    },
    availability,
    // Auth configuration extracted from layers
    systemSecrets,
    userSecrets,
    auth,
    // Legacy schemas (deprecated)
    secretsSchema: undefined,
    authSchema: undefined,
    tools,
    category: manifest.category,
    icon: buildIconUrl(manifest.id, manifest.icon),
    color: manifest.color,
    runtime: manifest.runtime,
    status: availability.enabled ? "active" : "disabled",
    createdAt: now,
    updatedAt: now,
  }
}

/**
 * Read all MCA manifests from the mcas directory with validation
 */
async function readManifests(): Promise<
  Map<string, { manifest: MCAManifest; dir: string; tools: string[] }>
> {
  const manifests = new Map<string, { manifest: MCAManifest; dir: string; tools: string[] }>()
  let hasErrors = false

  try {
    const entries = await readdir(MCAS_DIR, { withFileTypes: true })

    for (const entry of entries) {
      if (!entry.isDirectory()) continue
      if (!entry.name.startsWith("mca.")) continue

      const manifestPath = join(MCAS_DIR, entry.name, "manifest.json")
      const toolsPath = join(MCAS_DIR, entry.name, "tools.json")

      try {
        const content = await readFile(manifestPath, "utf-8")
        let data: unknown

        try {
          data = JSON.parse(content)
        } catch (parseErr) {
          console.error(`  ❌ ${entry.name}: Invalid JSON in manifest.json`)
          hasErrors = true
          continue
        }

        // Validate manifest against schema
        const validation = validateMCAManifest(data)

        if (!validation.valid) {
          console.error(formatValidationResult(entry.name, validation))
          hasErrors = true
          continue
        }

        const manifest = validation.manifest!

        // Show warnings but continue
        if (validation.warnings.length > 0) {
          console.warn(`  ⚠️  ${manifest.id}: ${validation.warnings.length} warning(s)`)
          validation.warnings.forEach((w) => {
            console.warn(`      - ${w.path}: ${w.message}`)
          })
        }

        // Read tools from tools.json
        let tools: string[] = []
        try {
          const toolsContent = await readFile(toolsPath, "utf-8")
          const toolsJson = JSON.parse(toolsContent) as ToolsJson
          tools = toolsJson.tools.map((t) => t.name)
        } catch {
          if (manifest.layers.tools) {
            console.warn(`  ⚠ No tools.json for ${entry.name} (but layers.tools is true)`)
          }
        }

        manifests.set(manifest.id, { manifest, dir: entry.name, tools })
        console.log(`  ✓ Valid: ${manifest.id} (${manifest.name}) - ${tools.length} tools`)
      } catch (err) {
        console.error(`  ❌ ${entry.name}: ${err instanceof Error ? err.message : "Unknown error"}`)
        hasErrors = true
      }
    }
  } catch (err) {
    console.error(`Error reading MCAs directory: ${err}`)
  }

  if (hasErrors) {
    console.error("\n❌ Some MCAs have validation errors. Fix them before syncing.")
    process.exit(1)
  }

  return manifests
}

/**
 * Sync manifests with database
 */
async function syncMcas(dryRun: boolean = false) {
  console.log("🔄 Syncing MCAs with database...\n")
  console.log(`MCAs directory: ${MCAS_DIR}\n`)

  // Read all manifests
  console.log("📂 Reading manifests...")
  const manifests = await readManifests()
  console.log(`\nFound ${manifests.size} MCAs\n`)

  if (manifests.size === 0) {
    console.log("No MCAs found. Nothing to sync.")
    return
  }

  // Load secrets and connect to MongoDB
  const secretsPath = join(__dirname, "../../../../.secrets")
  ;(secrets as any).basePath = secretsPath
  await secrets.load()

  const dbSecret = secrets.system("database")
  const mongoUri = process.env.MONGODB_URI || dbSecret?.uri || "mongodb://localhost:27017"
  const mongoDatabase = process.env.MONGODB_DATABASE || dbSecret?.database || "teros"

  const mongoClient = new MongoClient(mongoUri)

  try {
    await mongoClient.connect()
    const db = mongoClient.db(mongoDatabase)
    const catalogCollection = db.collection<McpCatalogEntry>("mca_catalog")

    // Get existing entries
    const existing = await catalogCollection.find({}).toArray()
    const existingMap = new Map(existing.map((e) => [e.mcaId, e]))

    console.log(`📊 Database has ${existing.length} existing entries\n`)

    // Determine changes - always force update for existing entries
    const toInsert: McpCatalogEntry[] = []
    const toUpdate: McpCatalogEntry[] = []

    for (const [mcaId, { manifest, dir, tools }] of manifests) {
      const catalogEntry = manifestToCatalogEntry(manifest, dir, tools)
      const existingEntry = existingMap.get(mcaId)

      if (!existingEntry) {
        toInsert.push(catalogEntry)
      } else {
        // Always update - preserve original createdAt timestamp
        catalogEntry.createdAt = existingEntry.createdAt
        catalogEntry.updatedAt = new Date().toISOString()
        toUpdate.push(catalogEntry)
      }
    }

    // Find entries in DB that no longer have manifests (orphans)
    const manifestIds = new Set(manifests.keys())
    const orphans = existing.filter((e) => !manifestIds.has(e.mcaId))

    // Report changes
    console.log("📋 Changes:")

    if (toInsert.length > 0) {
      console.log(`\n  New MCAs (${toInsert.length}):`)
      toInsert.forEach((e) => console.log(`    + ${e.mcaId} (${e.name})`))
    }

    if (toUpdate.length > 0) {
      console.log(`\n  Synced MCAs (${toUpdate.length}):`)
      toUpdate.forEach((e) => console.log(`    ~ ${e.mcaId} (${e.name})`))
    }

    if (orphans.length > 0) {
      console.log(`\n  🗑️  Orphaned catalog entries (no manifest found):`)
      orphans.forEach((e) => console.log(`    - ${e.mcaId} (${e.name})`))
    }

    // Apply changes
    if (dryRun) {
      console.log("\n🔍 DRY RUN - No changes applied\n")
    } else {
      console.log("\n💾 Applying changes...")

      // Insert new entries
      if (toInsert.length > 0) {
        await catalogCollection.insertMany(toInsert)
        console.log(`  Inserted ${toInsert.length} new entries`)
      }

      // Update existing entries
      for (const entry of toUpdate) {
        await catalogCollection.updateOne({ mcaId: entry.mcaId }, { $set: entry })
      }
      if (toUpdate.length > 0) {
        console.log(`  Updated ${toUpdate.length} entries`)
      }

      // Delete orphaned catalog entries (mcaId no longer has a manifest)
      if (orphans.length > 0) {
        const orphanIds = orphans.map((e) => e.mcaId)
        await catalogCollection.deleteMany({ mcaId: { $in: orphanIds } })
        console.log(`  Deleted ${orphans.length} orphaned catalog entries`)
      }

      console.log("\n✅ Sync complete!\n")

      // Delete orphaned apps (apps whose mcaId no longer exists in the active catalog)
      console.log("🧹 Checking for orphaned installed apps...")
      const mcaService = new McaService(db)
      const activeMcaIds = new Set(manifests.keys())
      const { deleted } = await mcaService.deleteOrphanedApps(activeMcaIds)

      if (deleted.length > 0) {
        console.log(`  🗑️  Deleted ${deleted.length} orphaned apps:`)
        deleted.forEach((a) => console.log(`    - ${a.appId} (${a.mcaId} / ${a.name})`))
      } else {
        console.log("  No orphaned apps found")
      }
    }

    // Summary
    console.log("\n📊 Summary:")
    console.log(`  Total MCAs in filesystem: ${manifests.size}`)
    console.log(`  Total entries in database: ${existing.length + toInsert.length}`)
    console.log(`  Inserted: ${toInsert.length}`)
    console.log(`  Synced: ${toUpdate.length}`)
    if (orphans.length > 0) {
      console.log(`  Deleted from catalog: ${orphans.length} orphaned entries`)
    }
  } catch (error) {
    console.error("Error syncing MCAs:", error)
    throw error
  } finally {
    await mongoClient.close()
  }
}

// Run if called directly
// Note: import.meta.main doesn't work with tsx, so we check if this is the main module
const isMain = import.meta.url === `file://${process.argv[1]}` || import.meta.main
if (isMain) {
  const args = process.argv.slice(2)
  const dryRun = args.includes("--dry-run")

  syncMcas(dryRun)
    .then(() => process.exit(0))
    .catch((error) => {
      console.error(error)
      process.exit(1)
    })
}

export { syncMcas }
