/**
 * Tool Executor Interface
 *
 * Defines the contract for tool executors that can be used by ConversationManager.
 * Implementations include MCPToolExecutor (core) and McaToolExecutor (backend).
 */

import type { ToolDefinition } from '../llm/ILLMClient';

/**
 * Attachment returned alongside a tool result
 */
export interface ToolAttachment {
  url: string;
  mime: string;
  filename?: string;
}

/**
 * Result from executing a tool
 */
export interface ToolExecutionResult {
  output: string;
  isError: boolean;
  /** MCP ID for renderer matching (optional for backward compatibility) */
  mcaId?: string;
  /** Attachments (images, files) generated by the tool */
  attachments?: ToolAttachment[];
}

/**
 * Options for tool execution
 */
export interface ToolExecutionOptions {
  /** The unique ID of this tool call (for tracking concurrent executions) */
  toolCallId?: string;
  /** Aborts the executor chain when the turn is cancelled. */
  signal?: AbortSignal;
  /**
   * Opaque correlation id for agent usage instrumentation. When present, the
   * executor emits tool.started / tool.ended events on the UsageEventBuffer
   * with the FK to the parent session. The core forwards the value as-is.
   */
  sessionUsageId?: string;
  /**
   * Step counter at dispatch time: 1 for tools produced by the FIRST LLM call
   * (TurnDriver increments `step` before dispatching). Used by tool_executions
   * for correlation with `llm_usage` (`llm_usage[step+1]` is the LLM call that
   * processed this tool's output). Do NOT renumber to 0-based without a data
   * migration — the persisted rows already carry this meaning (TER-445).
   */
  stepIndex?: number;
  /**
   * Index of the tool call within the step (0-based). Always 0 today because
   * execution is sequential; reserved for future parallel tool execution.
   */
  toolCallIndex?: number;
}

/**
 * Interface for tool executors
 *
 * ConversationManager uses this interface to:
 * 1. Get available tools to pass to LLM
 * 2. Execute tools when LLM requests them
 */
export interface IToolExecutor {
  /**
   * Get all available tools
   * Called by ConversationManager to pass to LLM
   */
  getTools(): ToolDefinition[];

  /**
   * Execute a tool call
   * Called by ConversationManager when LLM requests a tool
   *
   * @param toolName - Name of the tool to execute
   * @param input - Input parameters for the tool
   * @param options - Optional execution options (toolCallId for concurrent tool support)
   * @returns Tool output, error status, and optionally mcaId for renderer matching
   */
  executeTool(
    toolName: string,
    input: Record<string, any>,
    options?: ToolExecutionOptions,
  ): Promise<ToolExecutionResult>;

  /**
   * Get mcaId for a tool name (optional, for renderer matching)
   */
  getMcpIdForTool?(toolName: string): string | undefined;
}
