/**
 * MCA Connection Manager
 *
 * Manages WebSocket connections between backend and MCAs for bidirectional communication.
 *
 * Responsibilities:
 * - WebSocket server on /mca path for MCA connections
 * - Registry of active connections (appId → WebSocket)
 * - Heartbeat/ping-pong for connection health
 * - Event routing from MCAs to channels
 * - Subscription management for keep-alive
 *
 * Protocol:
 * - MCAs connect with: ws://localhost:PORT/mca?appId=xxx&token=yyy
 * - Token is generated by McaManager before spawn and expires in 30s
 * - Once connected, MCAs can send events, health updates, etc.
 * - Backend can send commands, subscription updates, etc.
 */

import {
  type HealthStatus,
  type McaConnection,
  type McaSubscription,
  type PendingConnection,
  parseMcaMessage,
  type WsBackendToMcaMessage,
  type WsHealthUpdate,
  type WsMcaEvent,
  type WsMcaToBackendMessage,
} from '@teros/shared';
import type { WsRouter } from '../ws-framework/WsRouter';
import { EventEmitter } from 'events';
import type { Server as HttpServer, IncomingMessage } from 'http';
import type { Collection, Db } from 'mongodb';
import { nanoid } from 'nanoid';
import { type RawData, WebSocket, WebSocketServer } from 'ws';
import { captureException } from '../lib/sentry';


// ============================================================================
// TYPES  (interfaces live in mca-connection-manager.types.ts)
// ============================================================================

import type { AuthManager } from '../auth/auth-manager';
import type { SecretsManager } from '../secrets/secrets-manager';
import { type BoardService, buildTaskInitialMessage } from './board-service';
import type { ChannelManager } from './channel-manager';
import type { WorkspaceService } from './workspace-service';
import type { VolumeService } from './volume-service';
import type { SessionManager } from './session-manager';
import type { PubSubService } from './pubsub-service';
import type { MCAEventSubscriptionService } from './mca-event-subscription-service';
import type {
  AppInfo,
  ActiveConnection,
  McaConnectionManagerConfig,
  QueryHandlerContext,
} from './mca-connection-manager.types';
export type { McaConnectionManagerEvents, McaConnectionManagerConfig } from './mca-connection-manager.types';
import { handleQueryConversations } from './mca-connection-manager.queries';

// MCA CONNECTION MANAGER
// ============================================================================

export class McaConnectionManager extends EventEmitter {
  private connections = new Map<string, ActiveConnection>();
  private pendingConnections = new Map<
    string,
    PendingConnection & { mcaId: string; ownerId: string }
  >();
  private wss: WebSocketServer | null = null;
  private pingInterval: NodeJS.Timeout | null = null;
  private subscriptionsCollection: Collection<McaSubscription>;

  private config: {
    pingIntervalMs: number;
    pongTimeoutMs: number;
    tokenExpiryMs: number;
  };
  private secretsManager?: SecretsManager;
  private authManager?: AuthManager;
  private channelManager?: ChannelManager;
  private boardService?: BoardService;
  private sessionManager?: SessionManager;
  private wsRouter?: WsRouter;
  private pubSubService?: PubSubService;
  private mcaEventSubscriptionService?: MCAEventSubscriptionService;
  private workspaceService?: WorkspaceService;
  private volumeService?: VolumeService;

  constructor(
    private db: Db,
    config?: McaConnectionManagerConfig,
  ) {
    super();
    this.config = {
      pingIntervalMs: config?.pingIntervalMs ?? 30000,
      pongTimeoutMs: config?.pongTimeoutMs ?? 10000,
      tokenExpiryMs: config?.tokenExpiryMs ?? 30000,
    };
    this.secretsManager = config?.secretsManager;
    this.authManager = config?.authManager;
    this.channelManager = config?.channelManager;
    this.boardService = config?.boardService;
    this.sessionManager = config?.sessionManager;
    this.wsRouter = config?.wsRouter;
    this.pubSubService = config?.pubSubService;
    this.mcaEventSubscriptionService = config?.mcaEventSubscriptionService;
    this.workspaceService = config?.workspaceService;
    this.volumeService = config?.volumeService;
    this.subscriptionsCollection = db.collection('mca_subscriptions');
  }

  // ==========================================================================
  // INITIALIZATION
  // ==========================================================================

  /**
   * Initialize WebSocket server (noServer mode - upgrade handled externally)
   */
  initWebSocketServer(_server: HttpServer): void {
    // Create WebSocket server in noServer mode
    // Upgrades are handled by handleUpgrade() called from index.ts
    this.wss = new WebSocketServer({ noServer: true });

    this.wss.on('connection', (ws, req) => {
      this.handleConnection(ws, req);
    });

    // Start ping interval
    this.startPingInterval();

    console.log('[McaConnectionManager] WebSocket server initialized (noServer mode)');
  }

  /**
   * Handle HTTP upgrade request for /mca path
   * Called from index.ts when upgrade request comes in
   */
  handleUpgrade(request: IncomingMessage, socket: any, head: Buffer): void {
    if (!this.wss) {
      console.error('[McaConnectionManager] WebSocket server not initialized');
      socket.destroy();
      return;
    }

    this.wss.handleUpgrade(request, socket, head, (ws) => {
      this.wss!.emit('connection', ws, request);
    });
  }

  /**
   * Ensure MongoDB indexes exist for subscriptions collection
   */
  async ensureIndexes(): Promise<void> {
    await this.subscriptionsCollection.createIndex({ appId: 1, status: 1 });
    await this.subscriptionsCollection.createIndex({ subscriptionId: 1 }, { unique: true });
    await this.subscriptionsCollection.createIndex({ 'subscriber.channelId': 1 });
    // TTL index for auto-expiry
    await this.subscriptionsCollection.createIndex(
      { 'options.expiresAt': 1 },
      { expireAfterSeconds: 0 },
    );
    console.log('[McaConnectionManager] MongoDB indexes created for mca_subscriptions');
  }

  // ==========================================================================
  // PENDING CONNECTIONS (called by McaManager before spawn)
  // ==========================================================================

  /**
   * Register a pending connection for an MCA about to spawn
   * Returns a token that the MCA must use to connect
   */
  registerPendingConnection(appId: string, mcaId: string, ownerId: string): string {
    // Clean up any existing pending connection for this appId
    this.pendingConnections.delete(appId);

    const token = nanoid(32);
    const now = Date.now();

    const pending = {
      appId,
      mcaId,
      ownerId,
      token,
      createdAt: now,
      expiresAt: now + this.config.tokenExpiryMs,
    };

    this.pendingConnections.set(appId, pending);
    console.log(
      `[McaConnectionManager] Registered pending connection for ${appId} (mcaId: ${mcaId}, ownerId: ${ownerId})`,
    );

    // Auto-cleanup expired pending connections
    setTimeout(() => {
      const current = this.pendingConnections.get(appId);
      if (current && current.token === token) {
        this.pendingConnections.delete(appId);
        console.log(`[McaConnectionManager] Pending connection expired for ${appId}`);
      }
    }, this.config.tokenExpiryMs + 1000);

    return token;
  }

  // ==========================================================================
  // CONNECTION HANDLING
  // ==========================================================================

  /**
   * Handle new WebSocket connection
   */
  private handleConnection(ws: WebSocket, req: IncomingMessage): void {
    const url = new URL(req.url || '', `http://${req.headers.host}`);
    const appId = url.searchParams.get('appId');
    const token = url.searchParams.get('token');

    // Validate parameters
    if (!appId || !token) {
      console.warn('[McaConnectionManager] Connection rejected: missing appId or token');
      ws.close(4001, 'Missing appId or token');
      return;
    }

    // Validate pending connection
    const pending = this.pendingConnections.get(appId);
    if (!pending) {
      console.warn(
        `[McaConnectionManager] Connection rejected: no pending connection for ${appId}`,
      );
      ws.close(4002, 'No pending connection');
      return;
    }

    if (pending.token !== token) {
      console.warn(`[McaConnectionManager] Connection rejected: invalid token for ${appId}`);
      ws.close(4003, 'Invalid token');
      return;
    }

    if (Date.now() > pending.expiresAt) {
      console.warn(`[McaConnectionManager] Connection rejected: token expired for ${appId}`);
      this.pendingConnections.delete(appId);
      ws.close(4004, 'Token expired');
      return;
    }

    // Connection valid - extract mcaId and ownerId, then clean up pending
    const { mcaId, ownerId } = pending;
    this.pendingConnections.delete(appId);

    // Close existing connection if any
    const existing = this.connections.get(appId);
    if (existing) {
      console.log(`[McaConnectionManager] Closing existing connection for ${appId}`);
      existing.ws.close(4005, 'Replaced by new connection');
    }

    // Register new connection
    const connection: ActiveConnection = {
      ws,
      appId,
      mcaId,
      ownerId,
      connectedAt: Date.now(),
      status: 'ready',
    };
    this.connections.set(appId, connection);

    console.log(
      `[McaConnectionManager] MCA connected: ${appId} (mcaId: ${mcaId}, ownerId: ${ownerId})`,
    );

    // Send connection acknowledgment
    this.send(appId, {
      type: 'connection_ack',
      appId,
      serverTime: Date.now(),
    });

    // Setup message handler
    ws.on('message', (data) => {
      this.handleMessage(appId, data);
    });

    // Setup close handler — pass the socket so handleDisconnect can ignore
    // the (async) close of a socket that was already replaced by a newer one.
    ws.on('close', (code, reason) => {
      this.handleDisconnect(appId, code, reason.toString(), ws);
    });

    // Setup error handler
    ws.on('error', (error) => {
      console.error(`[McaConnectionManager] WebSocket error for ${appId}:`, error.message);
    });

    // Emit connected event
    this.emit('mca:connected', appId);
  }

  /**
   * Handle incoming message from MCA
   */
  private handleMessage(appId: string, data: RawData): void {
    const connection = this.connections.get(appId);
    if (!connection) {
      console.warn(`[McaConnectionManager] Message from unknown appId: ${appId}`);
      return;
    }

    let message: WsMcaToBackendMessage | null = null;

    try {
      const parsed = JSON.parse(data.toString());
      message = parseMcaMessage(parsed);
    } catch (error) {
      console.error(`[McaConnectionManager] Failed to parse message from ${appId}:`, error);
      return;
    }

    if (!message) {
      console.warn(`[McaConnectionManager] Invalid message format from ${appId}`);
      return;
    }

    // Handle by message type
    switch (message.type) {
      case 'pong':
        connection.lastPongAt = Date.now();
        if (message.status) {
          connection.status = message.status;
        }
        break;

      case 'event':
        console.log(`[McaConnectionManager] Event from ${appId}: ${message.eventType}`);
        this.emit('mca:event', { ...message, appId });
        break;

      case 'health_update':
        console.log(`[McaConnectionManager] Health update from ${appId}: ${message.status}`);
        connection.status = message.status;
        this.emit('mca:health', appId, message);
        break;

      case 'credentials_expired':
        console.log(`[McaConnectionManager] Credentials expired for ${appId}: ${message.reason}`);
        this.emit('mca:credentials_expired', appId, message.reason);
        break;

      case 'error':
        console.error(
          `[McaConnectionManager] Error from ${appId}: ${message.code} - ${message.message}`,
        );
        break;

      case 'get_system_secrets':
        this.handleGetSystemSecrets(appId, connection, message.requestId);
        break;

      case 'get_user_secrets':
        this.handleGetUserSecrets(appId, connection, message.requestId);
        break;

      case 'update_user_secrets':
        this.handleUpdateUserSecrets(appId, connection, message.requestId, message.secrets);
        break;

      case 'query_conversations':
        this.handleQueryConversations(
          appId,
          connection,
          message.requestId,
          message.action,
          message.params,
        );
        break;

      case 'admin_request':
        this.handleAdminRequest(
          appId,
          connection,
          message.requestId,
          message.action,
          message.params ?? {},
        );
        break;
    }
  }

  /**
   * Handle get_system_secrets request
   */
  private handleGetSystemSecrets(
    appId: string,
    connection: ActiveConnection,
    requestId: string,
  ): void {
    console.log(`[McaConnectionManager] get_system_secrets request from ${appId}`);

    if (!this.secretsManager) {
      this.send(appId, {
        type: 'system_secrets',
        requestId,
        secrets: null,
        error: 'SecretsManager not available',
      });
      return;
    }

    try {
      const secrets = this.secretsManager.mca(connection.mcaId);
      console.log(
        `[McaConnectionManager] Sending system secrets to ${appId}: ${secrets ? Object.keys(secrets).join(', ') : 'null'}`,
      );

      this.send(appId, {
        type: 'system_secrets',
        requestId,
        secrets: secrets || null,
      });
    } catch (error) {
      console.error(`[McaConnectionManager] Error loading system secrets for ${appId}:`, error);
      captureException(error, { context: 'mca-load-system-secrets', appId });
      this.send(appId, {
        type: 'system_secrets',
        requestId,
        secrets: null,
        error: error instanceof Error ? error.message : 'Failed to load system secrets',
      });
    }
  }

  /**
   * Handle get_user_secrets request
   */
  private async handleGetUserSecrets(
    appId: string,
    connection: ActiveConnection,
    requestId: string,
  ): Promise<void> {
    console.log(
      `[McaConnectionManager] get_user_secrets request from ${appId} (ownerId: ${connection.ownerId})`,
    );

    if (!this.authManager) {
      this.send(appId, {
        type: 'user_secrets',
        requestId,
        secrets: null,
        error: 'AuthManager not available',
      });
      return;
    }

    try {
      const credentials = await this.authManager.get(connection.ownerId, appId);
      console.log(
        `[McaConnectionManager] Sending user secrets to ${appId}: ${credentials ? Object.keys(credentials).join(', ') : 'null'}`,
      );

      // Convert to Record<string, string> (credentials may have undefined values)
      let secrets: Record<string, string> | null = null;
      if (credentials) {
        secrets = {};
        for (const [key, value] of Object.entries(credentials)) {
          if (value !== undefined && value !== null) {
            secrets[key] = String(value);
          }
        }
      }

      this.send(appId, {
        type: 'user_secrets',
        requestId,
        secrets,
      });
    } catch (error) {
      console.error(`[McaConnectionManager] Error loading user secrets for ${appId}:`, error);
      captureException(error, { context: 'mca-load-user-secrets', appId });
      this.send(appId, {
        type: 'user_secrets',
        requestId,
        secrets: null,
        error: error instanceof Error ? error.message : 'Failed to load user secrets',
      });
    }
  }

  /**
   * Handle update_user_secrets request (MCA refreshed tokens locally)
   */
  private async handleUpdateUserSecrets(
    appId: string,
    connection: ActiveConnection,
    requestId: string,
    secrets: Record<string, string>,
  ): Promise<void> {
    console.log(
      `[McaConnectionManager] update_user_secrets request from ${appId}: ${Object.keys(secrets).join(', ')}`,
    );

    if (!this.authManager) {
      this.send(appId, {
        type: 'update_user_secrets_response',
        requestId,
        success: false,
        error: 'AuthManager not available',
      });
      return;
    }

    try {
      // Get existing credentials and merge with updates
      const existing = (await this.authManager.get(connection.ownerId, appId)) || {};
      const updated = { ...existing, ...secrets };

      // Save back to auth manager
      await this.authManager.set(connection.ownerId, appId, connection.mcaId, updated);

      console.log(`[McaConnectionManager] User secrets updated for ${appId}`);

      this.send(appId, {
        type: 'update_user_secrets_response',
        requestId,
        success: true,
      });
    } catch (error) {
      console.error(`[McaConnectionManager] Error updating user secrets for ${appId}:`, error);
      captureException(error, { context: 'mca-update-user-secrets', appId });
      this.send(appId, {
        type: 'update_user_secrets_response',
        requestId,
        success: false,
        error: error instanceof Error ? error.message : 'Failed to update user secrets',
      });
    }
  }

  /**
   * Handle query_conversations request
   */
  /**
   * Handle query_conversations — delegates to mca-connection-manager.queries.ts
   */
  private async handleQueryConversations(
    appId: string,
    connection: ActiveConnection,
    requestId: string,
    action: string,
    params: Record<string, unknown>,
  ): Promise<void> {
    const ctx: QueryHandlerContext = {
      db: this.db,
      channelManager: this.channelManager,
      boardService: this.boardService,
      pubSubService: this.pubSubService,
      mcaEventSubscriptionService: this.mcaEventSubscriptionService,
      workspaceService: this.workspaceService,
      volumeService: this.volumeService,
      wsRouter: this.wsRouter,
      send: this.send.bind(this),
      emit: this.emit.bind(this),
      resolveEffectiveAgentId: this.resolveEffectiveAgentId.bind(this),
      dispatchToRouter: this.dispatchToRouter.bind(this),
    };
    await handleQueryConversations(ctx, appId, connection, requestId, action, params);
  }

  /**
   * Handle MCA disconnect.
   *
   * The `ws` parameter guards against a race on replace: `close()` on the
   * OLD socket fires its 'close' event asynchronously, AFTER the new
   * connection for the same appId has been registered. Without the identity
   * check, that stale close would evict the LIVE connection from the Map
   * (send() → false, setContext → no-op) while its WebSocket is still open.
   */
  private handleDisconnect(appId: string, code: number, reason: string, ws?: WebSocket): void {
    const current = this.connections.get(appId);
    if (ws && current && current.ws !== ws) {
      console.log(
        `[McaConnectionManager] Ignoring stale close for ${appId} (code: ${code}) — connection already replaced`,
      );
      return;
    }
    this.connections.delete(appId);
    console.log(
      `[McaConnectionManager] MCA disconnected: ${appId} (code: ${code}, reason: ${reason})`,
    );
    this.emit('mca:disconnected', appId, reason || `Code ${code}`);
  }

  // ==========================================================================
  // SENDING MESSAGES
  // ==========================================================================

  /**
   * Send a message to an MCA
   */
  send(appId: string, message: WsBackendToMcaMessage): boolean {
    const connection = this.connections.get(appId);
    if (!connection) {
      return false;
    }

    if (connection.ws.readyState !== WebSocket.OPEN) {
      return false;
    }

    try {
      connection.ws.send(JSON.stringify(message));
      return true;
    } catch (error) {
      console.error(`[McaConnectionManager] Failed to send message to ${appId}:`, error);
      return false;
    }
  }

  /**
   * Send credentials update to MCA
   */
  sendCredentialsUpdate(appId: string, credentials: Record<string, string>): boolean {
    return this.send(appId, {
      type: 'credentials_updated',
      credentials,
    });
  }

  /**
   * Notify MCA of new subscription
   */
  sendSubscriptionAdded(appId: string, subscription: McaSubscription): boolean {
    return this.send(appId, {
      type: 'subscription_added',
      subscriptionId: subscription.subscriptionId,
      event: subscription.event,
      subscriber: subscription.subscriber,
      options: subscription.options
        ? {
            ttlMs: subscription.options.ttlMs,
            maxEvents: subscription.options.maxEvents,
            expiresAt: subscription.options.expiresAt?.toISOString(),
          }
        : undefined,
    });
  }

  /**
   * Notify MCA of removed subscription
   */
  sendSubscriptionRemoved(appId: string, subscriptionId: string, reason: string): boolean {
    return this.send(appId, {
      type: 'subscription_removed',
      subscriptionId,
      reason,
    });
  }

  /**
   * Send command to MCA
   */
  sendCommand(
    appId: string,
    command: 'shutdown' | 'reload' | 'health_check',
    params?: Record<string, unknown>,
  ): boolean {
    return this.send(appId, {
      type: 'command',
      command,
      params,
    });
  }

  // ==========================================================================
  // QUERIES
  // ==========================================================================

  /**
   * Check if an MCA is connected via WebSocket
   */
  isConnected(appId: string): boolean {
    const connection = this.connections.get(appId);
    return connection !== undefined && connection.ws.readyState === WebSocket.OPEN;
  }

  /**
   * Get connection info for an MCA
   */
  getConnection(appId: string): McaConnection | null {
    const connection = this.connections.get(appId);
    if (!connection) {
      return null;
    }

    return {
      appId: connection.appId,
      connectedAt: connection.connectedAt,
      lastPingAt: connection.lastPingAt,
      lastPongAt: connection.lastPongAt,
      status: connection.status,
      subscriptionCount: 0, // Will be populated from DB query
    };
  }

  /**
   * Resolve the effective agentId for an MCA connection.
   *
   * For stdio MCAs, `connection.currentAgentId` is set via `setContext` before
   * each tool call. For WebSocket/HTTP MCAs that send `query_conversations`
   * directly (not through the tool-call path), `currentAgentId` is always
   * undefined because `setContext` is deliberately skipped to avoid race
   * conditions on shared connection objects.
   *
   * In that case we fall back to querying `agent_app_access`: if exactly one
   * agent has access to this appId we use it; if multiple agents share the app
   * we accept an optional `agentIdHint` (sent by the MCA in the params payload)
   * and validate it against the grants — if it matches, we use it.
   * Only if no hint is provided or it doesn't match do we return undefined.
   */
  private async resolveEffectiveAgentId(
    connection: ActiveConnection,
    agentIdHint?: string,
  ): Promise<string | undefined> {
    if (connection.currentAgentId) {
      return connection.currentAgentId;
    }

    // Look up which agents have been granted access to this app
    const accessCollection = this.db.collection('agent_app_access');
    const grants = await accessCollection
      .find({ appId: connection.appId }, { projection: { agentId: 1 } })
      .toArray() as unknown as Array<{ agentId: string }>;

    if (grants.length === 1) {
      return grants[0].agentId;
    }

    // Multiple agents share this app — use the hint if it is a valid grant
    if (agentIdHint) {
      const isValidGrant = grants.some((g) => g.agentId === agentIdHint);
      if (isValidGrant) {
        return agentIdHint;
      }
    }

    // Cannot resolve unambiguously
    return undefined;
  }

  /**
   * Set execution context for an MCA (called before tool execution)
   * This is used for agent-to-agent communication - the MCA needs to know
   * which agent is currently using it.
   */
  setContext(appId: string, context: { agentId?: string; channelId?: string; workspaceId?: string }): void {
    const connection = this.connections.get(appId);
    if (connection) {
      connection.currentAgentId = context.agentId;
      connection.currentChannelId = context.channelId;
      connection.currentWorkspaceId = context.workspaceId;
    }
  }

  /**
   * Get all connected MCAs
   */
  getConnectedAppIds(): string[] {
    return Array.from(this.connections.keys());
  }

  /**
   * Check if an MCA has active subscriptions
   */
  async hasActiveSubscriptions(appId: string): Promise<boolean> {
    const count = await this.subscriptionsCollection.countDocuments({
      appId,
      status: 'active',
    });
    return count > 0;
  }

  /**
   * Get active subscription count for an MCA
   */
  async getActiveSubscriptionCount(appId: string): Promise<number> {
    return await this.subscriptionsCollection.countDocuments({
      appId,
      status: 'active',
    });
  }

  // ==========================================================================
  // SUBSCRIPTION MANAGEMENT
  // ==========================================================================

  /**
   * Create a new subscription
   */
  async createSubscription(
    appId: string,
    mcaId: string,
    subscriber: McaSubscription['subscriber'],
    event: McaSubscription['event'],
    options?: McaSubscription['options'],
  ): Promise<McaSubscription> {
    const now = new Date();
    const subscription: McaSubscription = {
      subscriptionId: `sub_${nanoid()}`,
      appId,
      mcaId,
      subscriber,
      event,
      options,
      status: 'active',
      eventsDelivered: 0,
      createdAt: now,
      updatedAt: now,
    };

    await this.subscriptionsCollection.insertOne(subscription as any);

    // Notify MCA if connected
    this.sendSubscriptionAdded(appId, subscription);

    console.log(
      `[McaConnectionManager] Created subscription ${subscription.subscriptionId} for ${appId}`,
    );
    return subscription;
  }

  /**
   * Get subscription by ID
   */
  async getSubscription(subscriptionId: string): Promise<McaSubscription | null> {
    return (await this.subscriptionsCollection.findOne({
      subscriptionId,
    })) as McaSubscription | null;
  }

  /**
   * Get subscriptions for a channel
   */
  async getSubscriptionsForChannel(channelId: string): Promise<McaSubscription[]> {
    return (await this.subscriptionsCollection
      .find({ 'subscriber.channelId': channelId, status: 'active' })
      .toArray()) as McaSubscription[];
  }

  /**
   * Cancel a subscription
   */
  async cancelSubscription(subscriptionId: string, reason: string): Promise<boolean> {
    const subscription = await this.getSubscription(subscriptionId);
    if (!subscription) {
      return false;
    }

    await this.subscriptionsCollection.updateOne(
      { subscriptionId },
      {
        $set: {
          status: 'expired',
          statusReason: reason,
          updatedAt: new Date(),
        },
      },
    );

    // Notify MCA if connected
    this.sendSubscriptionRemoved(subscription.appId, subscriptionId, reason);

    console.log(`[McaConnectionManager] Cancelled subscription ${subscriptionId}: ${reason}`);
    return true;
  }

  /**
   * Record event delivery for a subscription
   */
  async recordEventDelivery(subscriptionId: string): Promise<void> {
    const result = await this.subscriptionsCollection.findOneAndUpdate(
      { subscriptionId },
      {
        $inc: { eventsDelivered: 1 },
        $set: {
          lastEventAt: new Date(),
          updatedAt: new Date(),
        },
      },
      { returnDocument: 'after' },
    );

    // Check if maxEvents reached
    const subscription = result as McaSubscription | null;
    if (
      subscription?.options?.maxEvents &&
      subscription.eventsDelivered >= subscription.options.maxEvents
    ) {
      await this.cancelSubscription(subscriptionId, 'Max events reached');
    }
  }

  // ==========================================================================
  // HEARTBEAT
  // ==========================================================================

  /**
   * Start ping interval for all connections
   */
  private startPingInterval(): void {
    this.pingInterval = setInterval(() => {
      this.pingAllConnections();
    }, this.config.pingIntervalMs);
  }

  /**
   * Ping all connections and check for dead ones
   */
  private pingAllConnections(): void {
    const now = Date.now();

    for (const [appId, connection] of this.connections.entries()) {
      // Check if last pong is too old (connection might be dead)
      if (connection.lastPingAt && connection.lastPongAt) {
        const timeSinceLastPong = now - connection.lastPongAt;
        if (timeSinceLastPong > this.config.pingIntervalMs + this.config.pongTimeoutMs) {
          console.warn(`[McaConnectionManager] Connection dead (no pong): ${appId}`);
          connection.ws.close(4006, 'Pong timeout');
          continue;
        }
      }

      // Send ping
      connection.lastPingAt = now;
      this.send(appId, {
        type: 'ping',
        serverTime: now,
      });
    }
  }

  // ==========================================================================
  // LIFECYCLE
  // ==========================================================================

  /**
   * Shutdown the connection manager
   */
  async shutdown(): Promise<void> {
    console.log('[McaConnectionManager] Shutting down...');

    // Stop ping interval
    if (this.pingInterval) {
      clearInterval(this.pingInterval);
      this.pingInterval = null;
    }

    // Close all connections
    for (const [appId, connection] of this.connections.entries()) {
      console.log(`[McaConnectionManager] Closing connection: ${appId}`);
      connection.ws.close(1001, 'Server shutting down');
    }
    this.connections.clear();

    // Close WebSocket server
    if (this.wss) {
      await new Promise<void>((resolve) => {
        this.wss!.close(() => resolve());
      });
      this.wss = null;
    }

    console.log('[McaConnectionManager] Shutdown complete');
  }

  /**
   * Handle admin_request from MCA — dispatches to WsRouter admin-api domain.
   * The MCA's ownerId is used as the userId for the handler context.
   */
  private async handleAdminRequest(
    appId: string,
    connection: ActiveConnection,
    requestId: string,
    action: string,
    params: Record<string, unknown>,
  ): Promise<void> {
    console.log(`[McaConnectionManager] admin_request (${action}) from ${appId}`);

    if (!this.wsRouter) {
      this.send(appId, {
        type: 'admin_response',
        requestId,
        error: 'WsRouter not available',
        code: 'ROUTER_UNAVAILABLE',
      });
      return;
    }

    if (!this.wsRouter.has(action)) {
      this.send(appId, {
        type: 'admin_response',
        requestId,
        error: `Unknown action: ${action}`,
        code: 'UNKNOWN_ACTION',
      });
      return;
    }

    try {
      // Build a fake WebSocket that captures the response and forwards it to the MCA
      const self = this;
      const fakeWs = {
        readyState: 1, // OPEN
        send(payload: string) {
          try {
            const msg = JSON.parse(payload);
            if (msg.type === 'response') {
              self.send(appId, {
                type: 'admin_response',
                requestId,
                data: msg.data,
              });
            } else if (msg.type === 'error') {
              self.send(appId, {
                type: 'admin_response',
                requestId,
                error: msg.message,
                code: msg.code,
              });
            }
          } catch {
            // ignore parse errors
          }
        },
      } as unknown as import('ws').WebSocket;

      // Resolve the real userId: if ownerId is a workspace ID (starts with ws_ or work_),
      // look up the workspace owner. This is necessary because admin-api handlers call
      // requireAdmin(db, userId) which checks the `users` collection — workspace IDs
      // don't exist there and would always fail the admin check.
      let userId = connection.ownerId;
      if (userId?.startsWith('ws_') || userId?.startsWith('work_')) {
        const workspace = await this.db.collection('workspaces').findOne({ workspaceId: userId } as any);
        if ((workspace as any)?.ownerId) {
          userId = (workspace as any).ownerId;
          console.log(`[McaConnectionManager] admin_request: resolved workspace ${connection.ownerId} → user ${userId}`);
        }
      }

      // Use resolved userId; sessionId is synthetic for MCA context
      const ctx = { userId, sessionId: `mca:${appId}`, ip: `mca:${connection.mcaId}` };
      await this.wsRouter.dispatch(fakeWs, ctx, requestId, action, params);
    } catch (error) {
      console.error(`[McaConnectionManager] admin_request error for ${appId}:`, error);
      this.send(appId, {
        type: 'admin_response',
        requestId,
        error: error instanceof Error ? error.message : 'Internal error',
        code: 'INTERNAL_ERROR',
      });
    }
  }

  /**
   * Dispatch an action to the WsRouter and return the result data.
   * Used by query_conversations cases that delegate to board WsRouter handlers.
   * Resolves the real userId when ownerId is a workspace (same logic as handleQueryConversations).
   */
  private async dispatchToRouter(
    appId: string,
    connection: ActiveConnection,
    action: string,
    params: Record<string, unknown>,
  ): Promise<unknown> {
    // Resolve real userId: if ownerId is a workspace, look up the workspace owner
    let userId = connection.ownerId;
    if (userId?.startsWith('ws_') || userId?.startsWith('work_')) {
      const workspace = await this.db.collection('workspaces').findOne({ workspaceId: userId } as any);
      if ((workspace as any)?.ownerId) {
        userId = (workspace as any).ownerId;
      }
    }

    return new Promise((resolve, reject) => {
      const fakeWs = {
        readyState: 1,
        send(payload: string) {
          try {
            const msg = JSON.parse(payload);
            if (msg.type === 'response') {
              resolve(msg.data);
            } else if (msg.type === 'error') {
              reject(new Error(msg.message || msg.code || 'Unknown error'));
            }
          } catch {
            reject(new Error('Failed to parse router response'));
          }
        },
      } as unknown as import('ws').WebSocket;

      const ctx = { userId, sessionId: `mca:${appId}`, ip: `mca:${connection.mcaId}` };
      const requestId = `mca-dispatch-${Date.now()}`;
      this.wsRouter!.dispatch(fakeWs, ctx, requestId, action, params).catch(reject);
    });
  }

  /**
   * Get status for all connections (for admin/debugging)
   */
  getStatus(): {
    connectedCount: number;
    connections: Array<{
      appId: string;
      connectedAt: number;
      lastPongAt?: number;
      status: HealthStatus;
    }>;
  } {
    const connections = Array.from(this.connections.values()).map((c) => ({
      appId: c.appId,
      connectedAt: c.connectedAt,
      lastPongAt: c.lastPongAt,
      status: c.status,
    }));

    return {
      connectedCount: connections.length,
      connections,
    };
  }
}
