/**
 * MCA Connection Manager
 *
 * Manages WebSocket connections between backend and MCAs for bidirectional communication.
 *
 * Responsibilities:
 * - WebSocket server on /mca path for MCA connections
 * - Registry of active connections (appId → WebSocket)
 * - Heartbeat/ping-pong for connection health
 * - Event routing from MCAs to channels
 * - Subscription management for keep-alive
 *
 * Protocol:
 * - MCAs connect with: ws://localhost:PORT/mca?appId=xxx&token=yyy
 * - Token is generated by McaManager before spawn and expires in 30s
 * - Once connected, MCAs can send events, health updates, etc.
 * - Backend can send commands, subscription updates, etc.
 */

import {
  type HealthStatus,
  type McaConnection,
  type McaSubscription,
  type PendingConnection,
  parseMcaMessage,
  type WsBackendToMcaMessage,
  type WsHealthUpdate,
  type WsMcaEvent,
  type WsMcaToBackendMessage,
} from '@teros/shared';
import type { WsRouter } from '../ws-framework/WsRouter';
import { EventEmitter } from 'events';
import type { Server as HttpServer, IncomingMessage } from 'http';
import type { Collection, Db } from 'mongodb';
import { nanoid } from 'nanoid';
import { type RawData, WebSocket, WebSocketServer } from 'ws';
import { captureException } from '../lib/sentry';

// ============================================================================
// TYPES
// ============================================================================

import type { AuthManager } from '../auth/auth-manager';
import type { SecretsManager } from '../secrets/secrets-manager';
import { type BoardService, buildTaskInitialMessage } from './board-service';
import type { ChannelManager } from './channel-manager';
import type { SessionManager } from './session-manager';

/**
 * App info needed for secrets resolution
 */
interface AppInfo {
  appId: string;
  mcaId: string;
  ownerId: string;
}

/**
 * Active WebSocket connection with metadata
 */
interface ActiveConnection {
  ws: WebSocket;
  appId: string;
  mcaId: string; // Needed to load system secrets
  ownerId: string; // Needed to load user secrets
  connectedAt: number;
  lastPingAt?: number;
  lastPongAt?: number;
  status: HealthStatus;
  /** Current agent context - set before tool execution, used for agent-to-agent communication */
  currentAgentId?: string;
  /** Current channel context - set before tool execution */
  currentChannelId?: string;
  /** Current workspace context - set before tool execution */
  currentWorkspaceId?: string;
}

/**
 * Events emitted by McaConnectionManager
 */
export interface McaConnectionManagerEvents {
  'mca:connected': (appId: string) => void;
  'mca:disconnected': (appId: string, reason: string) => void;
  'mca:event': (event: WsMcaEvent & { appId: string }) => void;
  'mca:health': (appId: string, update: WsHealthUpdate) => void;
  'mca:credentials_expired': (appId: string, reason: string) => void;
  'mca:send_message': (data: { channelId: string; agentId: string; message: string }) => void;
}

/**
 * Configuration for McaConnectionManager
 */
export interface McaConnectionManagerConfig {
  /** Ping interval in ms (default: 30000) */
  pingIntervalMs?: number;
  /** Pong timeout in ms - connection considered dead if no pong (default: 10000) */
  pongTimeoutMs?: number;
  /** Token expiry time in ms (default: 30000) */
  tokenExpiryMs?: number;
  /** Secrets manager for loading system secrets */
  secretsManager?: SecretsManager;
  /** Auth manager for loading user secrets */
  authManager?: AuthManager;
  /** Channel manager for conversations queries */
  channelManager?: ChannelManager;
  /** Board service for board/task queries from MCAs */
  boardService?: BoardService;
  /** Session manager for broadcasting board events */
  sessionManager?: SessionManager;
  /** WsRouter for admin_request dispatch (admin-api domain) */
  wsRouter?: WsRouter;
}

// ============================================================================
// MCA CONNECTION MANAGER
// ============================================================================

export class McaConnectionManager extends EventEmitter {
  private connections = new Map<string, ActiveConnection>();
  private pendingConnections = new Map<
    string,
    PendingConnection & { mcaId: string; ownerId: string }
  >();
  private wss: WebSocketServer | null = null;
  private pingInterval: NodeJS.Timeout | null = null;
  private subscriptionsCollection: Collection<McaSubscription>;

  private config: {
    pingIntervalMs: number;
    pongTimeoutMs: number;
    tokenExpiryMs: number;
  };
  private secretsManager?: SecretsManager;
  private authManager?: AuthManager;
  private channelManager?: ChannelManager;
  private boardService?: BoardService;
  private sessionManager?: SessionManager;
  private wsRouter?: WsRouter;

  constructor(
    private db: Db,
    config?: McaConnectionManagerConfig,
  ) {
    super();
    this.config = {
      pingIntervalMs: config?.pingIntervalMs ?? 30000,
      pongTimeoutMs: config?.pongTimeoutMs ?? 10000,
      tokenExpiryMs: config?.tokenExpiryMs ?? 30000,
    };
    this.secretsManager = config?.secretsManager;
    this.authManager = config?.authManager;
    this.channelManager = config?.channelManager;
    this.boardService = config?.boardService;
    this.sessionManager = config?.sessionManager;
    this.wsRouter = config?.wsRouter;
    this.subscriptionsCollection = db.collection('mca_subscriptions');
  }

  /**
   * Broadcast a board event to all WebSocket sessions subscribed to a board.
   */
  private broadcastBoardEvent(boardId: string, event: Record<string, any>): void {
    if (!this.sessionManager) return;
    const subscribers = this.sessionManager.getBoardSubscribers(boardId);
    if (subscribers.length === 0) return;

    const payload = JSON.stringify(event);
    for (const session of subscribers) {
      if (session.ws && session.ws.readyState === 1) {
        session.ws.send(payload);
      }
    }
  }

  // ==========================================================================
  // INITIALIZATION
  // ==========================================================================

  /**
   * Initialize WebSocket server (noServer mode - upgrade handled externally)
   */
  initWebSocketServer(_server: HttpServer): void {
    // Create WebSocket server in noServer mode
    // Upgrades are handled by handleUpgrade() called from index.ts
    this.wss = new WebSocketServer({ noServer: true });

    this.wss.on('connection', (ws, req) => {
      this.handleConnection(ws, req);
    });

    // Start ping interval
    this.startPingInterval();

    console.log('[McaConnectionManager] WebSocket server initialized (noServer mode)');
  }

  /**
   * Handle HTTP upgrade request for /mca path
   * Called from index.ts when upgrade request comes in
   */
  handleUpgrade(request: IncomingMessage, socket: any, head: Buffer): void {
    if (!this.wss) {
      console.error('[McaConnectionManager] WebSocket server not initialized');
      socket.destroy();
      return;
    }

    this.wss.handleUpgrade(request, socket, head, (ws) => {
      this.wss!.emit('connection', ws, request);
    });
  }

  /**
   * Ensure MongoDB indexes exist for subscriptions collection
   */
  async ensureIndexes(): Promise<void> {
    await this.subscriptionsCollection.createIndex({ appId: 1, status: 1 });
    await this.subscriptionsCollection.createIndex({ subscriptionId: 1 }, { unique: true });
    await this.subscriptionsCollection.createIndex({ 'subscriber.channelId': 1 });
    // TTL index for auto-expiry
    await this.subscriptionsCollection.createIndex(
      { 'options.expiresAt': 1 },
      { expireAfterSeconds: 0 },
    );
    console.log('[McaConnectionManager] MongoDB indexes created for mca_subscriptions');
  }

  // ==========================================================================
  // PENDING CONNECTIONS (called by McaManager before spawn)
  // ==========================================================================

  /**
   * Register a pending connection for an MCA about to spawn
   * Returns a token that the MCA must use to connect
   */
  registerPendingConnection(appId: string, mcaId: string, ownerId: string): string {
    // Clean up any existing pending connection for this appId
    this.pendingConnections.delete(appId);

    const token = nanoid(32);
    const now = Date.now();

    const pending = {
      appId,
      mcaId,
      ownerId,
      token,
      createdAt: now,
      expiresAt: now + this.config.tokenExpiryMs,
    };

    this.pendingConnections.set(appId, pending);
    console.log(
      `[McaConnectionManager] Registered pending connection for ${appId} (mcaId: ${mcaId}, ownerId: ${ownerId})`,
    );

    // Auto-cleanup expired pending connections
    setTimeout(() => {
      const current = this.pendingConnections.get(appId);
      if (current && current.token === token) {
        this.pendingConnections.delete(appId);
        console.log(`[McaConnectionManager] Pending connection expired for ${appId}`);
      }
    }, this.config.tokenExpiryMs + 1000);

    return token;
  }

  // ==========================================================================
  // CONNECTION HANDLING
  // ==========================================================================

  /**
   * Handle new WebSocket connection
   */
  private handleConnection(ws: WebSocket, req: IncomingMessage): void {
    const url = new URL(req.url || '', `http://${req.headers.host}`);
    const appId = url.searchParams.get('appId');
    const token = url.searchParams.get('token');

    // Validate parameters
    if (!appId || !token) {
      console.warn('[McaConnectionManager] Connection rejected: missing appId or token');
      ws.close(4001, 'Missing appId or token');
      return;
    }

    // Validate pending connection
    const pending = this.pendingConnections.get(appId);
    if (!pending) {
      console.warn(
        `[McaConnectionManager] Connection rejected: no pending connection for ${appId}`,
      );
      ws.close(4002, 'No pending connection');
      return;
    }

    if (pending.token !== token) {
      console.warn(`[McaConnectionManager] Connection rejected: invalid token for ${appId}`);
      ws.close(4003, 'Invalid token');
      return;
    }

    if (Date.now() > pending.expiresAt) {
      console.warn(`[McaConnectionManager] Connection rejected: token expired for ${appId}`);
      this.pendingConnections.delete(appId);
      ws.close(4004, 'Token expired');
      return;
    }

    // Connection valid - extract mcaId and ownerId, then clean up pending
    const { mcaId, ownerId } = pending;
    this.pendingConnections.delete(appId);

    // Close existing connection if any
    const existing = this.connections.get(appId);
    if (existing) {
      console.log(`[McaConnectionManager] Closing existing connection for ${appId}`);
      existing.ws.close(4005, 'Replaced by new connection');
    }

    // Register new connection
    const connection: ActiveConnection = {
      ws,
      appId,
      mcaId,
      ownerId,
      connectedAt: Date.now(),
      status: 'ready',
    };
    this.connections.set(appId, connection);

    console.log(
      `[McaConnectionManager] MCA connected: ${appId} (mcaId: ${mcaId}, ownerId: ${ownerId})`,
    );

    // Send connection acknowledgment
    this.send(appId, {
      type: 'connection_ack',
      appId,
      serverTime: Date.now(),
    });

    // Setup message handler
    ws.on('message', (data) => {
      this.handleMessage(appId, data);
    });

    // Setup close handler
    ws.on('close', (code, reason) => {
      this.handleDisconnect(appId, code, reason.toString());
    });

    // Setup error handler
    ws.on('error', (error) => {
      console.error(`[McaConnectionManager] WebSocket error for ${appId}:`, error.message);
    });

    // Emit connected event
    this.emit('mca:connected', appId);
  }

  /**
   * Handle incoming message from MCA
   */
  private handleMessage(appId: string, data: RawData): void {
    const connection = this.connections.get(appId);
    if (!connection) {
      console.warn(`[McaConnectionManager] Message from unknown appId: ${appId}`);
      return;
    }

    let message: WsMcaToBackendMessage | null = null;

    try {
      const parsed = JSON.parse(data.toString());
      message = parseMcaMessage(parsed);
    } catch (error) {
      console.error(`[McaConnectionManager] Failed to parse message from ${appId}:`, error);
      return;
    }

    if (!message) {
      console.warn(`[McaConnectionManager] Invalid message format from ${appId}`);
      return;
    }

    // Handle by message type
    switch (message.type) {
      case 'pong':
        connection.lastPongAt = Date.now();
        if (message.status) {
          connection.status = message.status;
        }
        break;

      case 'event':
        console.log(`[McaConnectionManager] Event from ${appId}: ${message.eventType}`);
        this.emit('mca:event', { ...message, appId });
        break;

      case 'health_update':
        console.log(`[McaConnectionManager] Health update from ${appId}: ${message.status}`);
        connection.status = message.status;
        this.emit('mca:health', appId, message);
        break;

      case 'credentials_expired':
        console.log(`[McaConnectionManager] Credentials expired for ${appId}: ${message.reason}`);
        this.emit('mca:credentials_expired', appId, message.reason);
        break;

      case 'error':
        console.error(
          `[McaConnectionManager] Error from ${appId}: ${message.code} - ${message.message}`,
        );
        break;

      case 'get_system_secrets':
        this.handleGetSystemSecrets(appId, connection, message.requestId);
        break;

      case 'get_user_secrets':
        this.handleGetUserSecrets(appId, connection, message.requestId);
        break;

      case 'update_user_secrets':
        this.handleUpdateUserSecrets(appId, connection, message.requestId, message.secrets);
        break;

      case 'query_conversations':
        this.handleQueryConversations(
          appId,
          connection,
          message.requestId,
          message.action,
          message.params,
        );
        break;

      case 'admin_request':
        this.handleAdminRequest(
          appId,
          connection,
          message.requestId,
          message.action,
          message.params ?? {},
        );
        break;
    }
  }

  /**
   * Handle get_system_secrets request
   */
  private handleGetSystemSecrets(
    appId: string,
    connection: ActiveConnection,
    requestId: string,
  ): void {
    console.log(`[McaConnectionManager] get_system_secrets request from ${appId}`);

    if (!this.secretsManager) {
      this.send(appId, {
        type: 'system_secrets',
        requestId,
        secrets: null,
        error: 'SecretsManager not available',
      });
      return;
    }

    try {
      const secrets = this.secretsManager.mca(connection.mcaId);
      console.log(
        `[McaConnectionManager] Sending system secrets to ${appId}: ${secrets ? Object.keys(secrets).join(', ') : 'null'}`,
      );

      this.send(appId, {
        type: 'system_secrets',
        requestId,
        secrets: secrets || null,
      });
    } catch (error) {
      console.error(`[McaConnectionManager] Error loading system secrets for ${appId}:`, error);
      captureException(error, { context: 'mca-load-system-secrets', appId });
      this.send(appId, {
        type: 'system_secrets',
        requestId,
        secrets: null,
        error: error instanceof Error ? error.message : 'Failed to load system secrets',
      });
    }
  }

  /**
   * Handle get_user_secrets request
   */
  private async handleGetUserSecrets(
    appId: string,
    connection: ActiveConnection,
    requestId: string,
  ): Promise<void> {
    console.log(
      `[McaConnectionManager] get_user_secrets request from ${appId} (ownerId: ${connection.ownerId})`,
    );

    if (!this.authManager) {
      this.send(appId, {
        type: 'user_secrets',
        requestId,
        secrets: null,
        error: 'AuthManager not available',
      });
      return;
    }

    try {
      const credentials = await this.authManager.get(connection.ownerId, appId);
      console.log(
        `[McaConnectionManager] Sending user secrets to ${appId}: ${credentials ? Object.keys(credentials).join(', ') : 'null'}`,
      );

      // Convert to Record<string, string> (credentials may have undefined values)
      let secrets: Record<string, string> | null = null;
      if (credentials) {
        secrets = {};
        for (const [key, value] of Object.entries(credentials)) {
          if (value !== undefined && value !== null) {
            secrets[key] = String(value);
          }
        }
      }

      this.send(appId, {
        type: 'user_secrets',
        requestId,
        secrets,
      });
    } catch (error) {
      console.error(`[McaConnectionManager] Error loading user secrets for ${appId}:`, error);
      captureException(error, { context: 'mca-load-user-secrets', appId });
      this.send(appId, {
        type: 'user_secrets',
        requestId,
        secrets: null,
        error: error instanceof Error ? error.message : 'Failed to load user secrets',
      });
    }
  }

  /**
   * Handle update_user_secrets request (MCA refreshed tokens locally)
   */
  private async handleUpdateUserSecrets(
    appId: string,
    connection: ActiveConnection,
    requestId: string,
    secrets: Record<string, string>,
  ): Promise<void> {
    console.log(
      `[McaConnectionManager] update_user_secrets request from ${appId}: ${Object.keys(secrets).join(', ')}`,
    );

    if (!this.authManager) {
      this.send(appId, {
        type: 'update_user_secrets_response',
        requestId,
        success: false,
        error: 'AuthManager not available',
      });
      return;
    }

    try {
      // Get existing credentials and merge with updates
      const existing = (await this.authManager.get(connection.ownerId, appId)) || {};
      const updated = { ...existing, ...secrets };

      // Save back to auth manager
      await this.authManager.set(connection.ownerId, appId, connection.mcaId, updated);

      console.log(`[McaConnectionManager] User secrets updated for ${appId}`);

      this.send(appId, {
        type: 'update_user_secrets_response',
        requestId,
        success: true,
      });
    } catch (error) {
      console.error(`[McaConnectionManager] Error updating user secrets for ${appId}:`, error);
      captureException(error, { context: 'mca-update-user-secrets', appId });
      this.send(appId, {
        type: 'update_user_secrets_response',
        requestId,
        success: false,
        error: error instanceof Error ? error.message : 'Failed to update user secrets',
      });
    }
  }

  /**
   * Handle query_conversations request
   */
  private async handleQueryConversations(
    appId: string,
    connection: ActiveConnection,
    requestId: string,
    action: string,
    params: Record<string, unknown>,
  ): Promise<void> {
    console.log(`[McaConnectionManager] query_conversations (${action}) from ${appId}`);

    if (!this.channelManager) {
      this.send(appId, {
        type: 'query_conversations_result',
        requestId,
        action,
        data: null,
        error: 'ChannelManager not available',
      });
      return;
    }

    const userId = connection.ownerId;

    try {
      let data: unknown;

      switch (action) {
        case 'search_messages': {
          const query = params.query as string;
          const limit = (params.limit as number) || 50;
          const excludeChannelId = params.excludeChannelId as string | undefined;

          if (!query || query.length < 2) {
            throw new Error('Query must be at least 2 characters');
          }

          const results = await this.channelManager.searchMessages(userId, query, limit);

          // Filter out the current channel if specified
          if (excludeChannelId) {
            results.results = results.results.filter((r) => r.channelId !== excludeChannelId);
          }

          data = results;
          break;
        }

        case 'list_channels': {
          const status = params.status as 'active' | 'closed' | undefined;
          const limit = (params.limit as number) || 20;
          const excludeChannelId = params.excludeChannelId as string | undefined;

          const listResult = await this.channelManager.listUserChannels(userId, status, {
            limit,
          });

          let channels = listResult.channels;

          // Filter out private channels (MCAs should not access private conversations)
          channels = channels.filter((c) => !c.isPrivate);

          // Filter out the current channel if specified
          if (excludeChannelId) {
            channels = channels.filter((c) => c.channelId !== excludeChannelId);
          }

          data = {
            channels: channels.map((c) => ({
              channelId: c.channelId,
              name: c.metadata?.name || 'Chat',
              agentId: c.agentId,
              status: c.status,
              createdAt: c.createdAt,
              updatedAt: c.updatedAt,
              lastMessage: c.lastMessage,
            })),
            total: channels.length,
          };
          break;
        }

        case 'get_channel_messages': {
          const channelId = params.channelId as string;
          const limit = (params.limit as number) || 50;
          const before = params.before as string | undefined;
          const textOnly = params.textOnly !== false; // Default true

          if (!channelId) {
            throw new Error('channelId is required');
          }

          // Verify access (owner or workspace member)
          const channel = await this.channelManager.getChannel(channelId);
          if (!channel) {
            throw new Error('Channel not found');
          }
          const canAccess = await this.channelManager.canAccessChannel(channelId, userId);
          if (!canAccess) {
            throw new Error('Access denied');
          }

          // MCAs cannot access private channels
          if (channel.isPrivate) {
            throw new Error('Cannot access private conversation');
          }

          const result = await this.channelManager.getMessages(channelId, limit, before);

          // Filter to text-only if requested
          let messages = result.messages;
          if (textOnly) {
            messages = messages.filter((m) => m.content.type === 'text');
          }

          data = {
            channel: {
              channelId: channel.channelId,
              name: channel.metadata?.name || 'Chat',
              agentId: channel.agentId,
              status: channel.status,
              createdAt: channel.createdAt,
            },
            messages: messages.map((m) => ({
              messageId: m.messageId,
              role: m.role,
              content: m.content,
              timestamp: m.timestamp,
            })),
            hasMore: result.hasMore,
          };
          break;
        }

        case 'get_channel_summary': {
          const channelId = params.channelId as string;

          if (!channelId) {
            throw new Error('channelId is required');
          }

          // Verify access (owner or workspace member)
          const channel = await this.channelManager.getChannel(channelId);
          if (!channel) {
            throw new Error('Channel not found');
          }
          const canAccess = await this.channelManager.canAccessChannel(channelId, userId);
          if (!canAccess) {
            throw new Error('Access denied');
          }

          // MCAs cannot access private channels
          if (channel.isPrivate) {
            throw new Error('Cannot access private conversation');
          }

          // Get first and last messages
          const { messages: recentMessages } = await this.channelManager.getMessages(channelId, 1);
          const lastMessage = recentMessages[0];

          // Get message count (approximate by getting all and counting)
          // TODO: Add a count method to ChannelManager for efficiency
          const { messages: allMessages } = await this.channelManager.getMessages(channelId, 1000);
          const messageCount = allMessages.length;

          // Find first message (oldest)
          const firstMessage = allMessages[allMessages.length - 1];

          data = {
            channelId: channel.channelId,
            name: channel.metadata?.name || 'Chat',
            agentId: channel.agentId,
            status: channel.status,
            createdAt: channel.createdAt,
            updatedAt: channel.updatedAt,
            messageCount,
            firstMessage: firstMessage
              ? {
                  content:
                    firstMessage.content.type === 'text'
                      ? (firstMessage.content as any).text?.substring(0, 200)
                      : `[${firstMessage.content.type}]`,
                  timestamp: firstMessage.timestamp,
                  role: firstMessage.role,
                }
              : null,
            lastMessage: lastMessage
              ? {
                  content:
                    lastMessage.content.type === 'text'
                      ? (lastMessage.content as any).text?.substring(0, 200)
                      : `[${lastMessage.content.type}]`,
                  timestamp: lastMessage.timestamp,
                  role: lastMessage.role,
                }
              : null,
          };
          break;
        }

        case 'create_channel': {
          const agentId = params.agentId as string;
          const name = params.name as string | undefined;

          if (!agentId) {
            throw new Error('agentId is required');
          }

          // Create the channel
          const newChannel = await this.channelManager.createChannel(
            userId,
            agentId,
            name ? { name } : undefined,
          );

          data = {
            channelId: newChannel.channelId,
            agentId: newChannel.agentId,
            name: newChannel.metadata?.name || 'New conversation',
            status: newChannel.status,
            createdAt: newChannel.createdAt,
            updatedAt: newChannel.updatedAt,
          };
          break;
        }

        case 'send_message': {
          const channelId = params.channelId as string;
          const message = params.message as string;
          const senderAgentId = params.senderAgentId as string | undefined;

          if (!channelId) {
            throw new Error('channelId is required');
          }
          if (!message || message.trim().length === 0) {
            throw new Error('message is required and cannot be empty');
          }

          // Verify channel exists and user has access
          const channel = await this.channelManager.getChannel(channelId);
          if (!channel) {
            throw new Error('Channel not found');
          }
          const canAccess = await this.channelManager.canAccessChannel(channelId, userId);
          if (!canAccess) {
            throw new Error('Access denied');
          }

          // Create and save the message
          const messageId = this.channelManager.createMessageId();
          const timestamp = new Date().toISOString();

          // Get sender info - if senderAgentId provided (or from connection context), it's agent-to-agent communication
          // Priority: explicit param > connection context > user
          const effectiveAgentId = senderAgentId || connection.currentAgentId;
          let sender: { type: 'user' | 'agent'; id: string; name: string } | undefined;
          if (effectiveAgentId) {
            sender = (await this.channelManager.getAgentSender(effectiveAgentId)) || undefined;
          } else {
            sender = (await this.channelManager.getUserSender(userId)) || undefined;
          }

          const userMessage = {
            messageId,
            channelId,
            role: 'user' as const,
            userId,
            sender,
            content: { type: 'text' as const, text: message },
            timestamp,
          };

          await this.channelManager.saveMessage(userMessage);

          // Emit event so MessageHandler can process the agent response
          // This is done via the 'mca:send_message' event
          this.emit('mca:send_message', {
            channelId,
            agentId: channel.agentId,
            message: message,
          });

          data = {
            success: true,
            messageId,
            channelId,
            timestamp,
          };
          break;
        }

        case 'rename_channel': {
          const channelId = params.channelId as string;
          const name = params.name as string;

          if (!channelId) {
            throw new Error('channelId is required');
          }
          if (!name || name.trim().length === 0) {
            throw new Error('name is required and cannot be empty');
          }

          const channel = await this.channelManager.getChannel(channelId);
          if (!channel) {
            throw new Error('Channel not found');
          }

          // Verify access
          const canAccess = await this.channelManager.canAccessChannel(channelId, userId);
          if (!canAccess) {
            throw new Error('Access denied');
          }

          await this.channelManager.renameChannel(channelId, name.trim());

          data = {
            success: true,
            channelId,
            name: name.trim(),
          };
          break;
        }

        // ==================================================================
        // BOARD / TASK QUERIES
        // ==================================================================

        case 'get_tasks_by_agent': {
          if (!this.boardService) {
            throw new Error('BoardService not available');
          }
          const workspaceId = params.workspaceId as string;
          const agentId = params.agentId as string;
          if (!workspaceId || !agentId) {
            throw new Error('workspaceId and agentId are required');
          }
          const tasks = await this.boardService.getTasksByAgent(workspaceId, agentId);
          data = { agentId, tasks };
          break;
        }

        case 'get_board_summary': {
          if (!this.boardService) {
            throw new Error('BoardService not available');
          }
          const gbsProjectId = params.projectId as string;
          if (!gbsProjectId) {
            throw new Error('projectId is required');
          }
          const gbsProject = await this.boardService.getProject(gbsProjectId);
          if (!gbsProject) {
            throw new Error('Project not found');
          }
          const summary = await this.boardService.getBoardSummary(gbsProject.boardId);
          if (!summary) {
            throw new Error('Board not found');
          }
          data = summary;
          break;
        }

        case 'list_tasks': {
          if (!this.boardService) {
            throw new Error('BoardService not available');
          }
          const ltProjectId = params.projectId as string;
          if (!ltProjectId) {
            throw new Error('projectId is required');
          }
          const project = await this.boardService.getProject(ltProjectId);
          if (!project) {
            throw new Error('Project not found');
          }
          const { projectId: _pid, ...filters } = params;
          const filteredTasks = await this.boardService.listTasks(project.boardId, filters as any);
          data = { projectId: ltProjectId, tasks: filteredTasks };
          break;
        }

        case 'get_task': {
          if (!this.boardService) {
            throw new Error('BoardService not available');
          }
          const taskId = params.taskId as string;
          if (!taskId) {
            throw new Error('taskId is required');
          }
          const task = await this.boardService.getTask(taskId);
          if (!task) {
            throw new Error('Task not found');
          }
          const allTasks = await this.boardService.listTasks(task.boardId, {});
          const subTasks = allTasks.filter((t: any) => t.parentTaskId === taskId);
          data = { task, subTasks };
          break;
        }

        case 'list_projects': {
          if (!this.boardService) {
            throw new Error('BoardService not available');
          }
          const lpWorkspaceId = params.workspaceId as string;
          if (!lpWorkspaceId) {
            throw new Error('workspaceId is required');
          }
          const projects = await this.boardService.listProjects(lpWorkspaceId);
          data = { workspaceId: lpWorkspaceId, projects };
          break;
        }

        case 'create_project': {
          if (!this.boardService) {
            throw new Error('BoardService not available');
          }
          const cpWorkspaceId = params.workspaceId as string;
          const cpName = params.name as string;
          const cpDescription = params.description as string | undefined;
          if (!cpWorkspaceId || !cpName) {
            throw new Error('workspaceId and name are required');
          }
          const { project: newProject, board: newBoard } = await this.boardService.createProject(
            cpWorkspaceId,
            userId,
            { name: cpName, description: cpDescription },
          );
          data = { project: newProject, board: newBoard };
          break;
        }

        case 'create_task': {
          if (!this.boardService) {
            throw new Error('BoardService not available');
          }
          const ctProjectId = params.projectId as string;
          if (!ctProjectId) {
            throw new Error('projectId is required');
          }
          const ctProject = await this.boardService.getProject(ctProjectId);
          if (!ctProject) {
            throw new Error('Project not found');
          }
          const { projectId: _ctPid, ...taskInput } = params;
          const newTask = await this.boardService.createTask(
            ctProject.boardId,
            userId,
            taskInput as any,
          );
          data = { task: newTask };
          this.broadcastBoardEvent(ctProject.boardId, {
            type: 'board_task_created',
            task: newTask,
          });
          break;
        }

        case 'batch_create_tasks': {
          if (!this.boardService) {
            throw new Error('BoardService not available');
          }
          const bctProjectId = params.projectId as string;
          const bctTasks = params.tasks as any[];
          if (!bctProjectId || !bctTasks || !Array.isArray(bctTasks)) {
            throw new Error('projectId and tasks array are required');
          }
          const bctProject = await this.boardService.getProject(bctProjectId);
          if (!bctProject) {
            throw new Error('Project not found');
          }
          const createdTasks = await this.boardService.batchCreateTasks(
            bctProject.boardId,
            userId,
            bctTasks,
          );
          data = { projectId: bctProjectId, tasks: createdTasks, count: createdTasks.length };
          this.broadcastBoardEvent(bctProject.boardId, {
            type: 'board_tasks_batch_created',
            tasks: createdTasks,
          });
          break;
        }

        case 'update_task': {
          if (!this.boardService) {
            throw new Error('BoardService not available');
          }
          const utTaskId = params.taskId as string;
          if (!utTaskId) {
            throw new Error('taskId is required');
          }
          const { taskId: _utTid, ...updateInput } = params;
          const updatedTask = await this.boardService.updateTask(
            utTaskId,
            userId,
            updateInput as any,
          );
          if (!updatedTask) {
            throw new Error('Task not found');
          }
          data = { task: updatedTask };
          this.broadcastBoardEvent(updatedTask.boardId, {
            type: 'board_task_updated',
            task: updatedTask,
          });
          break;
        }

        case 'move_task': {
          if (!this.boardService) {
            throw new Error('BoardService not available');
          }
          const mtTaskId = params.taskId as string;
          const mtColumnId = params.columnId as string;
          const mtPosition = params.position as number | undefined;
          if (!mtTaskId || !mtColumnId) {
            throw new Error('taskId and columnId are required');
          }
          const movedTask = await this.boardService.moveTask(
            mtTaskId,
            userId,
            mtColumnId,
            mtPosition,
          );
          if (!movedTask) {
            throw new Error('Task not found');
          }
          data = { task: movedTask };
          this.broadcastBoardEvent(movedTask.boardId, {
            type: 'board_task_updated',
            task: movedTask,
          });
          break;
        }

        case 'assign_task': {
          if (!this.boardService) {
            throw new Error('BoardService not available');
          }
          const atTaskId = params.taskId as string;
          const atAgentId = params.agentId as string | undefined;
          if (!atTaskId) {
            throw new Error('taskId is required');
          }
          const assignedTask = await this.boardService.assignTask(atTaskId, userId, atAgentId);
          if (!assignedTask) {
            throw new Error('Task not found');
          }
          data = { task: assignedTask };
          this.broadcastBoardEvent(assignedTask.boardId, {
            type: 'board_task_updated',
            task: assignedTask,
          });
          break;
        }

        case 'start_task': {
          if (!this.boardService || !this.channelManager) {
            throw new Error('BoardService or ChannelManager not available');
          }
          const stTaskId = params.taskId as string;
          const stAgentId = params.agentId as string | undefined;
          const stPrompt = params.prompt as string | undefined;
          if (!stTaskId) {
            throw new Error('taskId is required');
          }
          const { task: startedTask } = await this.boardService.startTask(
            stTaskId,
            userId,
            stAgentId,
          );
          const assignedAgentId = startedTask.assignedAgentId!;

          // Reuse existing conversation or create a new one
          let channel: any;
          if (startedTask.channelId) {
            channel = await this.channelManager.getChannel(startedTask.channelId);
          }
          if (!channel) {
            channel = await this.channelManager.createChannel(userId, assignedAgentId, {
              name: startedTask.title,
            });
            await this.boardService.linkConversation(startedTask.taskId, userId, channel.channelId);
          }

          // Save origin channel (the channel that called start_task) for event notifications
          const originChannelId = connection.currentChannelId;
          if (originChannelId) {
            await this.boardService.setOriginChannel(startedTask.taskId, originChannelId);
          }

          const startedFullTask = { ...startedTask, channelId: channel.channelId, originChannelId };
          data = {
            task: startedFullTask,
            channelId: channel.channelId,
          };
          this.broadcastBoardEvent(startedTask.boardId, {
            type: 'board_task_updated',
            task: startedFullTask,
          });

          // Build and send initial message to the agent (fire-and-forget)
          const initialMessage = buildTaskInitialMessage(startedTask, stPrompt);

          try {
            // Save the initial message
            const msgId = this.channelManager.createMessageId();
            const msgTimestamp = new Date().toISOString();
            const sender = (await this.channelManager.getUserSender(userId)) || undefined;

            await this.channelManager.saveMessage({
              messageId: msgId,
              channelId: channel.channelId,
              role: 'user' as const,
              userId,
              sender,
              content: { type: 'text' as const, text: initialMessage },
              timestamp: msgTimestamp,
            });

            // Emit event so MessageHandler processes the agent response
            this.emit('mca:send_message', {
              channelId: channel.channelId,
              agentId: assignedAgentId,
              message: initialMessage,
            });
          } catch (err: any) {
            console.error(`❌ Error sending initial task message to ${channel.channelId}:`, err);
          }

          break;
        }

        case 'link_conversation': {
          if (!this.boardService) {
            throw new Error('BoardService not available');
          }
          const lcTaskId = params.taskId as string;
          const lcChannelId = params.channelId as string;
          if (!lcTaskId || !lcChannelId) {
            throw new Error('taskId and channelId are required');
          }
          const linkedTask = await this.boardService.linkConversation(
            lcTaskId,
            userId,
            lcChannelId,
          );
          if (!linkedTask) {
            throw new Error('Task not found');
          }
          data = { task: linkedTask };
          this.broadcastBoardEvent(linkedTask.boardId, {
            type: 'board_task_updated',
            task: linkedTask,
          });
          break;
        }

        case 'delete_task': {
          if (!this.boardService) {
            throw new Error('BoardService not available');
          }
          const dtTaskId = params.taskId as string;
          if (!dtTaskId) {
            throw new Error('taskId is required');
          }
          // Get task before deleting for broadcast
          const dtTask = await this.boardService.getTask(dtTaskId);
          const deleted = await this.boardService.deleteTask(dtTaskId);
          if (!deleted) {
            throw new Error('Task not found');
          }
          data = { taskId: dtTaskId, deleted: true };
          if (dtTask) {
            this.broadcastBoardEvent(dtTask.boardId, {
              type: 'board_task_deleted',
              taskId: dtTaskId,
            });
          }
          break;
        }

        case 'update_task_status': {
          if (!this.boardService) {
            throw new Error('BoardService not available');
          }
          const utsTaskId = params.taskId as string;
          const utsStatus = params.status as string;
          const utsActor = params.actor as string || userId;
          if (!utsTaskId || !utsStatus) {
            throw new Error('taskId and status are required');
          }
          const validStatuses = ['idle', 'assigned', 'working', 'blocked', 'review', 'done'];
          if (!validStatuses.includes(utsStatus)) {
            throw new Error(`Invalid status: ${utsStatus}. Must be one of: ${validStatuses.join(', ')}`);
          }
          const statusResult = await this.boardService.updateTaskStatus(
            utsTaskId,
            utsStatus as any,
            utsActor,
          );
          if (!statusResult) {
            throw new Error('Task not found');
          }
          data = { task: statusResult.task, previousStatus: statusResult.previousStatus };
          this.broadcastBoardEvent(statusResult.task.boardId, {
            type: 'board_task_updated',
            task: statusResult.task,
          });
          break;
        }

        case 'add_progress_note': {
          if (!this.boardService) {
            throw new Error('BoardService not available');
          }
          const apnTaskId = params.taskId as string;
          const apnText = params.text as string;
          const apnActor = params.actor as string || userId;
          if (!apnTaskId || !apnText) {
            throw new Error('taskId and text are required');
          }
          const noteTask = await this.boardService.addProgressNote(apnTaskId, apnText, apnActor);
          if (!noteTask) {
            throw new Error('Task not found');
          }
          data = { task: noteTask };
          this.broadcastBoardEvent(noteTask.boardId, {
            type: 'board_task_updated',
            task: noteTask,
          });
          break;
        }

        case 'move_my_task': {
          if (!this.boardService) {
            throw new Error('BoardService not available');
          }
          const mmtTaskId = params.taskId as string;
          const mmtAgentId = params.agentId as string;
          const mmtColumnId = params.columnId as string;
          const mmtPosition = params.position as number | undefined;
          if (!mmtTaskId || !mmtAgentId || !mmtColumnId) {
            throw new Error('taskId, agentId and columnId are required');
          }
          const mmtTask = await this.boardService.getTask(mmtTaskId);
          if (!mmtTask) {
            throw new Error('Task not found');
          }
          if (mmtTask.assignedAgentId !== mmtAgentId) {
            throw new Error('Agent is not assigned to this task');
          }
          const mmtMoved = await this.boardService.moveTask(
            mmtTaskId,
            userId,
            mmtColumnId,
            mmtPosition,
          );
          if (!mmtMoved) {
            throw new Error('Task not found');
          }
          data = { task: mmtMoved };
          this.broadcastBoardEvent(mmtMoved.boardId, {
            type: 'board_task_updated',
            task: mmtMoved,
          });
          break;
        }

        case 'update_my_task_status': {
          if (!this.boardService) {
            throw new Error('BoardService not available');
          }
          const umtsTaskId = params.taskId as string;
          const umtsAgentId = params.agentId as string;
          const umtsStatus = params.status as string;
          if (!umtsTaskId || !umtsAgentId || !umtsStatus) {
            throw new Error('taskId, agentId and status are required');
          }
          const validStatuses = ['idle', 'assigned', 'working', 'blocked', 'review', 'done'];
          if (!validStatuses.includes(umtsStatus)) {
            throw new Error(`Invalid status: ${umtsStatus}. Must be one of: ${validStatuses.join(', ')}`);
          }
          const umtsTask = await this.boardService.getTask(umtsTaskId);
          if (!umtsTask) {
            throw new Error('Task not found');
          }
          if (umtsTask.assignedAgentId !== umtsAgentId) {
            throw new Error('Agent is not assigned to this task');
          }
          const umtsResult = await this.boardService.updateTaskStatus(
            umtsTaskId,
            umtsStatus as any,
            umtsAgentId,
          );
          if (!umtsResult) {
            throw new Error('Task not found');
          }
          data = { task: umtsResult.task, previousStatus: umtsResult.previousStatus };
          this.broadcastBoardEvent(umtsResult.task.boardId, {
            type: 'board_task_updated',
            task: umtsResult.task,
          });
          break;
        }

        case 'add_my_progress_note': {
          if (!this.boardService) {
            throw new Error('BoardService not available');
          }
          const ampnTaskId = params.taskId as string;
          const ampnAgentId = params.agentId as string;
          const ampnText = params.text as string;
          if (!ampnTaskId || !ampnAgentId || !ampnText) {
            throw new Error('taskId, agentId and text are required');
          }
          const ampnTask = await this.boardService.getTask(ampnTaskId);
          if (!ampnTask) {
            throw new Error('Task not found');
          }
          if (ampnTask.assignedAgentId !== ampnAgentId) {
            throw new Error('Agent is not assigned to this task');
          }
          const ampnNoteTask = await this.boardService.addProgressNote(ampnTaskId, ampnText, ampnAgentId);
          if (!ampnNoteTask) {
            throw new Error('Task not found');
          }
          data = { task: ampnNoteTask };
          this.broadcastBoardEvent(ampnNoteTask.boardId, {
            type: 'board_task_updated',
            task: ampnNoteTask,
          });
          break;
        }

        default:
          throw new Error(`Unknown action: ${action}`);
      }

      this.send(appId, {
        type: 'query_conversations_result',
        requestId,
        action,
        data,
      });
    } catch (error) {
      console.error(`[McaConnectionManager] Error in query_conversations (${action}):`, error);
      captureException(error, { context: 'mca-query-conversations', appId, action });
      this.send(appId, {
        type: 'query_conversations_result',
        requestId,
        action,
        data: null,
        error: error instanceof Error ? error.message : 'Query failed',
      });
    }
  }

  /**
   * Handle MCA disconnect
   */
  private handleDisconnect(appId: string, code: number, reason: string): void {
    this.connections.delete(appId);
    console.log(
      `[McaConnectionManager] MCA disconnected: ${appId} (code: ${code}, reason: ${reason})`,
    );
    this.emit('mca:disconnected', appId, reason || `Code ${code}`);
  }

  // ==========================================================================
  // SENDING MESSAGES
  // ==========================================================================

  /**
   * Send a message to an MCA
   */
  send(appId: string, message: WsBackendToMcaMessage): boolean {
    const connection = this.connections.get(appId);
    if (!connection) {
      return false;
    }

    if (connection.ws.readyState !== WebSocket.OPEN) {
      return false;
    }

    try {
      connection.ws.send(JSON.stringify(message));
      return true;
    } catch (error) {
      console.error(`[McaConnectionManager] Failed to send message to ${appId}:`, error);
      return false;
    }
  }

  /**
   * Send credentials update to MCA
   */
  sendCredentialsUpdate(appId: string, credentials: Record<string, string>): boolean {
    return this.send(appId, {
      type: 'credentials_updated',
      credentials,
    });
  }

  /**
   * Notify MCA of new subscription
   */
  sendSubscriptionAdded(appId: string, subscription: McaSubscription): boolean {
    return this.send(appId, {
      type: 'subscription_added',
      subscriptionId: subscription.subscriptionId,
      event: subscription.event,
      subscriber: subscription.subscriber,
      options: subscription.options
        ? {
            ttlMs: subscription.options.ttlMs,
            maxEvents: subscription.options.maxEvents,
            expiresAt: subscription.options.expiresAt?.toISOString(),
          }
        : undefined,
    });
  }

  /**
   * Notify MCA of removed subscription
   */
  sendSubscriptionRemoved(appId: string, subscriptionId: string, reason: string): boolean {
    return this.send(appId, {
      type: 'subscription_removed',
      subscriptionId,
      reason,
    });
  }

  /**
   * Send command to MCA
   */
  sendCommand(
    appId: string,
    command: 'shutdown' | 'reload' | 'health_check',
    params?: Record<string, unknown>,
  ): boolean {
    return this.send(appId, {
      type: 'command',
      command,
      params,
    });
  }

  // ==========================================================================
  // QUERIES
  // ==========================================================================

  /**
   * Check if an MCA is connected via WebSocket
   */
  isConnected(appId: string): boolean {
    const connection = this.connections.get(appId);
    return connection !== undefined && connection.ws.readyState === WebSocket.OPEN;
  }

  /**
   * Get connection info for an MCA
   */
  getConnection(appId: string): McaConnection | null {
    const connection = this.connections.get(appId);
    if (!connection) {
      return null;
    }

    return {
      appId: connection.appId,
      connectedAt: connection.connectedAt,
      lastPingAt: connection.lastPingAt,
      lastPongAt: connection.lastPongAt,
      status: connection.status,
      subscriptionCount: 0, // Will be populated from DB query
    };
  }

  /**
   * Set execution context for an MCA (called before tool execution)
   * This is used for agent-to-agent communication - the MCA needs to know
   * which agent is currently using it.
   */
  setContext(appId: string, context: { agentId?: string; channelId?: string; workspaceId?: string }): void {
    const connection = this.connections.get(appId);
    if (connection) {
      connection.currentAgentId = context.agentId;
      connection.currentChannelId = context.channelId;
      connection.currentWorkspaceId = context.workspaceId;
    }
  }

  /**
   * Get all connected MCAs
   */
  getConnectedAppIds(): string[] {
    return Array.from(this.connections.keys());
  }

  /**
   * Check if an MCA has active subscriptions
   */
  async hasActiveSubscriptions(appId: string): Promise<boolean> {
    const count = await this.subscriptionsCollection.countDocuments({
      appId,
      status: 'active',
    });
    return count > 0;
  }

  /**
   * Get active subscription count for an MCA
   */
  async getActiveSubscriptionCount(appId: string): Promise<number> {
    return await this.subscriptionsCollection.countDocuments({
      appId,
      status: 'active',
    });
  }

  // ==========================================================================
  // SUBSCRIPTION MANAGEMENT
  // ==========================================================================

  /**
   * Create a new subscription
   */
  async createSubscription(
    appId: string,
    mcaId: string,
    subscriber: McaSubscription['subscriber'],
    event: McaSubscription['event'],
    options?: McaSubscription['options'],
  ): Promise<McaSubscription> {
    const now = new Date();
    const subscription: McaSubscription = {
      subscriptionId: `sub_${nanoid()}`,
      appId,
      mcaId,
      subscriber,
      event,
      options,
      status: 'active',
      eventsDelivered: 0,
      createdAt: now,
      updatedAt: now,
    };

    await this.subscriptionsCollection.insertOne(subscription as any);

    // Notify MCA if connected
    this.sendSubscriptionAdded(appId, subscription);

    console.log(
      `[McaConnectionManager] Created subscription ${subscription.subscriptionId} for ${appId}`,
    );
    return subscription;
  }

  /**
   * Get subscription by ID
   */
  async getSubscription(subscriptionId: string): Promise<McaSubscription | null> {
    return (await this.subscriptionsCollection.findOne({
      subscriptionId,
    })) as McaSubscription | null;
  }

  /**
   * Get subscriptions for a channel
   */
  async getSubscriptionsForChannel(channelId: string): Promise<McaSubscription[]> {
    return (await this.subscriptionsCollection
      .find({ 'subscriber.channelId': channelId, status: 'active' })
      .toArray()) as McaSubscription[];
  }

  /**
   * Cancel a subscription
   */
  async cancelSubscription(subscriptionId: string, reason: string): Promise<boolean> {
    const subscription = await this.getSubscription(subscriptionId);
    if (!subscription) {
      return false;
    }

    await this.subscriptionsCollection.updateOne(
      { subscriptionId },
      {
        $set: {
          status: 'expired',
          statusReason: reason,
          updatedAt: new Date(),
        },
      },
    );

    // Notify MCA if connected
    this.sendSubscriptionRemoved(subscription.appId, subscriptionId, reason);

    console.log(`[McaConnectionManager] Cancelled subscription ${subscriptionId}: ${reason}`);
    return true;
  }

  /**
   * Record event delivery for a subscription
   */
  async recordEventDelivery(subscriptionId: string): Promise<void> {
    const result = await this.subscriptionsCollection.findOneAndUpdate(
      { subscriptionId },
      {
        $inc: { eventsDelivered: 1 },
        $set: {
          lastEventAt: new Date(),
          updatedAt: new Date(),
        },
      },
      { returnDocument: 'after' },
    );

    // Check if maxEvents reached
    const subscription = result as McaSubscription | null;
    if (
      subscription?.options?.maxEvents &&
      subscription.eventsDelivered >= subscription.options.maxEvents
    ) {
      await this.cancelSubscription(subscriptionId, 'Max events reached');
    }
  }

  // ==========================================================================
  // HEARTBEAT
  // ==========================================================================

  /**
   * Start ping interval for all connections
   */
  private startPingInterval(): void {
    this.pingInterval = setInterval(() => {
      this.pingAllConnections();
    }, this.config.pingIntervalMs);
  }

  /**
   * Ping all connections and check for dead ones
   */
  private pingAllConnections(): void {
    const now = Date.now();

    for (const [appId, connection] of this.connections.entries()) {
      // Check if last pong is too old (connection might be dead)
      if (connection.lastPingAt && connection.lastPongAt) {
        const timeSinceLastPong = now - connection.lastPongAt;
        if (timeSinceLastPong > this.config.pingIntervalMs + this.config.pongTimeoutMs) {
          console.warn(`[McaConnectionManager] Connection dead (no pong): ${appId}`);
          connection.ws.close(4006, 'Pong timeout');
          continue;
        }
      }

      // Send ping
      connection.lastPingAt = now;
      this.send(appId, {
        type: 'ping',
        serverTime: now,
      });
    }
  }

  // ==========================================================================
  // LIFECYCLE
  // ==========================================================================

  /**
   * Shutdown the connection manager
   */
  async shutdown(): Promise<void> {
    console.log('[McaConnectionManager] Shutting down...');

    // Stop ping interval
    if (this.pingInterval) {
      clearInterval(this.pingInterval);
      this.pingInterval = null;
    }

    // Close all connections
    for (const [appId, connection] of this.connections.entries()) {
      console.log(`[McaConnectionManager] Closing connection: ${appId}`);
      connection.ws.close(1001, 'Server shutting down');
    }
    this.connections.clear();

    // Close WebSocket server
    if (this.wss) {
      await new Promise<void>((resolve) => {
        this.wss!.close(() => resolve());
      });
      this.wss = null;
    }

    console.log('[McaConnectionManager] Shutdown complete');
  }

  /**
   * Handle admin_request from MCA — dispatches to WsRouter admin-api domain.
   * The MCA's ownerId is used as the userId for the handler context.
   */
  private async handleAdminRequest(
    appId: string,
    connection: ActiveConnection,
    requestId: string,
    action: string,
    params: Record<string, unknown>,
  ): Promise<void> {
    console.log(`[McaConnectionManager] admin_request (${action}) from ${appId}`);

    if (!this.wsRouter) {
      this.send(appId, {
        type: 'admin_response',
        requestId,
        error: 'WsRouter not available',
        code: 'ROUTER_UNAVAILABLE',
      });
      return;
    }

    if (!this.wsRouter.has(action)) {
      this.send(appId, {
        type: 'admin_response',
        requestId,
        error: `Unknown action: ${action}`,
        code: 'UNKNOWN_ACTION',
      });
      return;
    }

    try {
      // Build a fake WebSocket that captures the response and forwards it to the MCA
      const self = this;
      const fakeWs = {
        readyState: 1, // OPEN
        send(payload: string) {
          try {
            const msg = JSON.parse(payload);
            if (msg.type === 'response') {
              self.send(appId, {
                type: 'admin_response',
                requestId,
                data: msg.data,
              });
            } else if (msg.type === 'error') {
              self.send(appId, {
                type: 'admin_response',
                requestId,
                error: msg.message,
                code: msg.code,
              });
            }
          } catch {
            // ignore parse errors
          }
        },
      } as unknown as import('ws').WebSocket;

      // Use ownerId as userId; sessionId is synthetic for MCA context
      const ctx = { userId: connection.ownerId, sessionId: `mca:${appId}`, ip: `mca:${connection.mcaId}` };
      await this.wsRouter.dispatch(fakeWs, ctx, requestId, action, params);
    } catch (error) {
      console.error(`[McaConnectionManager] admin_request error for ${appId}:`, error);
      this.send(appId, {
        type: 'admin_response',
        requestId,
        error: error instanceof Error ? error.message : 'Internal error',
        code: 'INTERNAL_ERROR',
      });
    }
  }

  /**
   * Get status for all connections (for admin/debugging)
   */
  getStatus(): {
    connectedCount: number;
    connections: Array<{
      appId: string;
      connectedAt: number;
      lastPongAt?: number;
      status: HealthStatus;
    }>;
  } {
    const connections = Array.from(this.connections.values()).map((c) => ({
      appId: c.appId,
      connectedAt: c.connectedAt,
      lastPongAt: c.lastPongAt,
      status: c.status,
    }));

    return {
      connectedCount: connections.length,
      connections,
    };
  }
}
