/**
 * Script to generate the list of valid Lucide icon names from @tamagui/lucide-icons.
 * Reads icon files from the dist/cjs/icons directory, converts PascalCase to kebab-case,
 * and outputs a Set constant to packages/shared/src/generated/lucide-icons.ts
 *
 * Usage: bun run generate-icons
 */

import { readdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Path to the lucide icons directory (root node_modules)
const iconsDir = join(__dirname, '../../../node_modules/@tamagui/lucide-icons/dist/cjs/icons');

// Output file
const outputFile = join(__dirname, '../src/generated/lucide-icons.ts');

/**
 * Convert PascalCase to kebab-case.
 * e.g., 'GitBranch' -> 'git-branch'
 * e.g., 'AArrowDown' -> 'a-arrow-down'
 */
function pascalToKebab(str: string): string {
  return str
    // Insert hyphen before sequences of uppercase letters followed by lowercase (e.g. AArrow -> A-Arrow)
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
    // Insert hyphen before uppercase letter preceded by lowercase letter or digit
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .toLowerCase();
}

// Read all .cjs files (one per icon, no native variants)
const files = readdirSync(iconsDir).filter(
  (f) => f.endsWith('.cjs') && !f.includes('.native')
);

const iconNames = files
  .map((f) => {
    const name = f.replace(/\.cjs$/, '');
    return pascalToKebab(name);
  })
  .sort();

console.log(`Found ${iconNames.length} icons`);
console.log('Sample:', iconNames.slice(0, 10));

// Verify key icons are present
const checks = ['folder', 'sailboat', 'git-branch', 'arrow-up'];
for (const check of checks) {
  const found = iconNames.includes(check);
  console.log(`  ${found ? '✓' : '✗'} ${check}`);
}

// Generate the output file
const content = `/**
 * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
 * Generated by: packages/shared/scripts/generate-lucide-icons.ts
 * Run \`bun run generate-icons\` in packages/shared to regenerate.
 *
 * Contains all valid Lucide icon names (kebab-case) from @tamagui/lucide-icons.
 * Total: ${iconNames.length} icons
 */

export const LUCIDE_ICONS: ReadonlySet<string> = new Set([
${iconNames.map((n) => `  '${n}',`).join('\n')}
]);
`;

writeFileSync(outputFile, content, 'utf-8');
console.log(`\nGenerated: ${outputFile}`);
console.log(`Total icons: ${iconNames.length}`);
